import pandas as pd
from pathlib import Path

lemma_senses = {
    'alto': 'tall; high',
    'americano': 'American',
    'anziano': 'elderly; aged',
    'aperto': 'open',
    'arrabbiato': 'angry',
    'assente': 'absent',
    'bianco': 'white',
    'blu': 'blue',
    'bravo': 'good; skillful; well-behaved',
    'breve': 'short; brief',
    'brutto': 'ugly; bad-looking',
    'caldo': 'hot; warm',
    'capace': 'able; capable',
    'carino': 'cute; nice',
    'cattivo': 'bad; mean; naughty',
    'chiaro': 'clear; bright',
    'cinese': 'Chinese',
    'colpevole': 'guilty',
    'contento': 'happy; content',
    'contrario': 'opposite; contrary; against',
    'costoso': 'expensive; costly',
    'difficile': 'difficult; hard',
    'diverso': 'different; various',
    'divertente': 'fun; entertaining',
    'duro': 'hard; tough',
    'economico': 'cheap; economical',
    'facile': 'easy; simple',
    'famoso': 'famous; well-known',
    'fastidioso': 'annoying; bothersome',
    'favorevole': 'favorable; supportive',
    'fiero': 'proud',
    'forte': 'strong; powerful',
    'fortunato': 'lucky; fortunate',
    'fotografico': 'photographic',
    'francese': 'French',
    'freddo': 'cold; chilly',
    'fresco': 'fresh; cool',
    'geloso': 'jealous',
    'gentile': 'kind; nice',
    'giapponese': 'Japanese',
    'giovane': 'young',
    'giusto': 'right; just; fair',
    'grasso': 'fat; overweight',
    'grosso': 'big; large',
    'importante': 'important',
    'impossibile': 'impossible',
    'inglese': 'English',
    'innocente': 'innocent',
    'intelligente': 'intelligent; smart',
    'interessante': 'interesting',
    'interessato': 'interested; concerned',
    'libero': 'free',
    'lontano': 'far; distant',
    'lungo': 'long',
    'maggiore': 'greater; elder',
    'malato': 'sick; ill',
    'migliore': 'better; best',
    'minimo': 'minimal; least',
    'necessario': 'necessary; needed',
    'nero': 'black',
    'nervoso': 'nervous; tense',
    'noioso': 'boring',
    'onesto': 'honest',
    'orgoglioso': 'proud',
    'pazzo': 'crazy; insane',
    'perfetto': 'perfect',
    'pericoloso': 'dangerous',
    'piccolo': 'small; little',
    'pieno': 'full',
    'pigro': 'lazy',
    'popolare': 'popular; well-liked',
    'possibile': 'possible',
    'povero': 'poor; unfortunate',
    'preferito': 'favorite',
    'preoccupato': 'worried; concerned',
    'pronto': 'ready',
    'prossimo': 'next; upcoming; near',
    'pulito': 'clean',
    'ricco': 'rich; wealthy',
    'rosso': 'red',
    'sbagliato': 'wrong; mistaken',
    'secondo': 'second',
    'semplice': 'simple; easy',
    'serio': 'serious',
    'stesso': 'same',
    'straniero': 'foreign; foreign-born',
    'strano': 'strange; odd',
    'stupido': 'stupid; dumb',
    'superiore': 'superior; higher',
    'tale': 'such; that kind of',
    'tedesco': 'German',
    'terribile': 'terrible; awful',
    'timido': 'shy; timid',
    'triste': 'sad',
    'ubriaco': 'drunk; intoxicated',
    'ultimo': 'last; final',
    'umano': 'human',
    'unico': 'unique; only',
    'vecchio': 'old',
    'veloce': 'fast; quick',
    'vicino': 'near; nearby',
    'vivo': 'alive; living',
}

special_translations = {
    "brav'": 'good; skillful; well-behaved (masculine, before a vowel)',
    'bravissimo': 'very good; excellent (masculine)',
    'bravissimi': 'very good; excellent (masculine plural)',
    'contentissimi': 'very happy; delighted (masculine plural)',
    'divertentissima': 'very fun; hilarious (feminine)',
    'divertentissimo': 'very fun; hilarious (masculine)',
    'divertentissimi': 'very fun; hilarious (masculine plural)',
    'durissima': 'very hard; extremely tough (feminine)',
    'durissimo': 'very hard; extremely tough (masculine)',
    'facilissimo': 'very easy; super easy (masculine)',
    'famosissimo': 'very famous; renowned (masculine)',
    'importantissimo': 'very important; crucial (masculine)',
    'interessantissime': 'very interesting; fascinating (feminine plural)',
    'noiosissimo': 'very boring; incredibly dull (masculine)',
    'piccolissimo': 'very small; tiny (masculine)',
    'semplicissimi': 'very simple; super easy (masculine plural)',
    'vicinissime': 'very close; extremely near (feminine plural)',
    'maggior': 'greater; elder (short form)',
    'miglior': 'better; best (short form)',
    "pover'": 'poor; unfortunate (masculine, before a vowel)',
}

pronunciations = {
    'alto': 'AHL-toh',
    'alta': 'AHL-tah',
    'alti': 'AHL-tee',
    'alte': 'AHL-teh',
    'americano': 'ah-meh-ree-KAH-noh',
    'americana': 'ah-meh-ree-KAH-nah',
    'americani': 'ah-meh-ree-KAH-nee',
    'americane': 'ah-meh-ree-KAH-neh',
    'anziano': 'ahn-TSYAH-noh',
    'anziana': 'ahn-TSYAH-nah',
    'anziane': 'ahn-TSYAH-neh',
    'anziani': 'ahn-TSYAH-nee',
    'aperta': 'ah-PEHR-tah',
    'aperti': 'ah-PEHR-tee',
    'aperte': 'ah-PEHR-teh',
    'aperto': 'ah-PEHR-toh',
    'arrabbiato': 'ahr-rahb-BYAH-toh',
    'arrabbiata': 'ahr-rahb-BYAH-tah',
    'arrabbiati': 'ahr-rahb-BYAH-tee',
    'arrabbiate': 'ahr-rahb-BYAH-teh',
    'assente': 'ah-SSEHN-teh',
    'assenti': 'ah-SSEHN-tee',
    'bianco': 'BYAHN-koh',
    'bianca': 'BYAHN-kah',
    'bianchi': 'BYAHN-kee',
    'bianche': 'BYAHN-keh',
    'blu': 'BLOO',
    'bravo': 'BRAH-voh',
    'brava': 'BRAH-vah',
    'bravi': 'BRAH-vee',
    'brave': 'BRAH-veh',
    "brav'": 'BRAHV',
    'bravissimo': 'brah-VEES-see-moh',
    'bravissimi': 'brah-VEES-see-mee',
    'breve': 'BREH-veh',
    'brevi': 'BREH-vee',
    'brutto': 'BROO-toh',
    'brutta': 'BROO-tah',
    'brutte': 'BROO-teh',
    'brutti': 'BROO-tee',
    'caldo': 'KAHL-doh',
    'calda': 'KAHL-dah',
    'calde': 'KAHL-deh',
    'caldi': 'KAHL-dee',
    'capace': 'kah-PAH-cheh',
    'capaci': 'kah-PAH-chee',
    'carina': 'kah-REE-nah',
    'carino': 'kah-REE-noh',
    'carini': 'kah-REE-nee',
    'carine': 'kah-REE-neh',
    'cattivo': 'kaht-TEE-voh',
    'cattiva': 'kaht-TEE-vah',
    'cattive': 'kaht-TEE-veh',
    'cattivi': 'kaht-TEE-vee',
    'chiaro': 'KYA-roh',
    'chiara': 'KYA-rah',
    'chiare': 'KYA-reh',
    'chiari': 'KYA-ree',
    'cinese': 'chee-NEH-seh',
    'cinesi': 'chee-NEH-see',
    'colpevole': 'kohl-PEH-voh-leh',
    'colpevoli': 'kohl-PEH-voh-lee',
    'contento': 'kohn-TEHN-toh',
    'contenta': 'kohn-TEHN-tah',
    'contenti': 'kohn-TEHN-tee',
    'contente': 'kohn-TEHN-teh',
    'contentissimi': 'kohn-tehn-TEES-see-mee',
    'contrario': 'kohn-TRAH-ryoh',
    'contraria': 'kohn-TRAH-ryah',
    'contrari': 'kohn-TRAH-ryee',
    'contrarie': 'kohn-TRAH-ryeh',
    'costoso': 'koh-STOH-zoh',
    'costosa': 'koh-STOH-zah',
    'costosi': 'koh-STOH-zee',
    'costose': 'koh-STOH-zeh',
    'difficile': 'dee-FEE-cheh-leh',
    'difficili': 'dee-FEE-chee-lee',
    'diverso': 'dee-VEHR-soh',
    'diversa': 'dee-VEHR-sah',
    'diverse': 'dee-VEHR-seh',
    'divertente': 'dee-vehr-TEHN-teh',
    'divertenti': 'dee-vehr-TEHN-tee',
    'divertentissima': 'dee-vehr-ten-TEES-see-mah',
    'divertentissimo': 'dee-vehr-ten-TEES-see-moh',
    'divertentissimi': 'dee-vehr-ten-TEES-see-mee',
    'duro': 'DOO-roh',
    'dura': 'DOO-rah',
    'dure': 'DOO-reh',
    'duri': 'DOO-ree',
    'durissima': 'doo-REES-see-mah',
    'durissimo': 'doo-REES-see-moh',
    'economico': 'eh-koh-NOH-mee-koh',
    'economica': 'eh-koh-NOH-mee-kah',
    'economici': 'eh-koh-NOH-mee-kee',
    'economiche': 'eh-koh-NOH-mee-keh',
    'facile': 'FAH-cheh-leh',
    'facili': 'FAH-chee-lee',
    'facilissimo': 'fah-chee-LEE-see-moh',
    'famoso': 'fah-MOH-zoh',
    'famosa': 'fah-MOH-zah',
    'famosi': 'fah-MOH-zee',
    'famose': 'fah-MOH-zeh',
    'famosissimo': 'fah-moh-ZEES-see-moh',
    'fastidioso': 'fah-stee-DYOH-zoh',
    'fastidiosa': 'fah-stee-DYOH-zah',
    'fastidiose': 'fah-stee-DYOH-zeh',
    'fastidiosi': 'fah-stee-DYOH-zee',
    'favorevole': 'fah-voh-REH-voh-leh',
    'favorevoli': 'fah-voh-REH-voh-lee',
    'fiero': 'FYAY-roh',
    'fieri': 'FYAY-ree',
    'fiera': 'FYAY-rah',
    'forte': 'FOR-teh',
    'forti': 'FOR-tee',
    'fortunato': 'for-too-NAH-toh',
    'fortunata': 'for-too-NAH-tah',
    'fortunati': 'for-too-NAH-tee',
    'fortunate': 'for-too-NAH-teh',
    'fotografica': 'foh-toh-GRAH-fee-kah',
    'fotografiche': 'foh-toh-GRAH-fee-keh',
    'fotografico': 'foh-toh-GRAH-fee-koh',
    'francese': 'frahn-CHEH-zeh',
    'francesi': 'frahn-CHEH-zee',
    'freddo': 'FREHD-doh',
    'fredda': 'FREHD-dah',
    'freddi': 'FREHD-dee',
    'fredde': 'FREHD-deh',
    'fresco': 'FREHS-koh',
    'fresca': 'FREHS-kah',
    'freschi': 'FREHS-kee',
    'fresche': 'FREHS-keh',
    'gelosa': 'jeh-LOH-zah',
    'geloso': 'jeh-LOH-zoh',
    'gelose': 'jeh-LOH-zeh',
    'gelosi': 'jeh-LOH-zee',
    'gentile': 'jen-TEE-leh',
    'gentili': 'jen-TEE-lee',
    'giapponese': 'jahp-poh-NEH-zeh',
    'giapponesi': 'jahp-poh-NEH-zee',
    'giovane': 'JYOH-vah-neh',
    'giovani': 'JYOH-vah-nee',
    'giusto': 'JYOO-stoh',
    'giusta': 'JYOO-stah',
    'giuste': 'JYOO-steh',
    'grasso': 'GRAHS-soh',
    'grassa': 'GRAHS-sah',
    'grassi': 'GRAHS-see',
    'grasse': 'GRAHS-seh',
    'grosso': 'GROHS-soh',
    'grossa': 'GROHS-sah',
    'grosse': 'GROHS-seh',
    'grossi': 'GROHS-see',
    'importante': 'eem-por-TAHN-teh',
    'importanti': 'eem-por-TAHN-tee',
    'importantissimo': 'eem-por-tahn-TEES-see-moh',
    'impossibile': 'eem-poh-SEE-bee-leh',
    'impossibili': 'eem-poh-SEE-bee-lee',
    'inglese': 'een-GLAY-zeh',
    'inglesi': 'een-GLAY-zee',
    'innocente': 'een-noh-CHEHN-teh',
    'innocenti': 'een-noh-CHEHN-tee',
    'intelligente': 'een-tehl-lee-JEHN-teh',
    'intelligenti': 'een-tehl-lee-JEHN-tee',
    'interessante': 'een-teh-reh-SAHN-teh',
    'interessanti': 'een-teh-reh-SAHN-tee',
    'interessantissime': 'een-teh-reh-sahn-TEES-see-meh',
    'interessato': 'een-teh-reh-SAH-toh',
    'interessata': 'een-teh-reh-SAH-tah',
    'interessati': 'een-teh-reh-SAH-tee',
    'interessate': 'een-teh-reh-SAH-teh',
    'libero': 'LEE-beh-roh',
    'libera': 'LEE-beh-rah',
    'liberi': 'LEE-beh-ree',
    'libere': 'LEE-beh-reh',
    'lontana': 'lohn-TAH-nah',
    'lontano': 'lohn-TAH-noh',
    'lontane': 'lohn-TAH-neh',
    'lontani': 'lohn-TAH-nee',
    'lungo': 'LOON-goh',
    'lunga': 'LOON-gah',
    'lunghi': 'LOON-ghee',
    'lunghe': 'LOON-geh',
    'maggior': 'mah-JOHR',
    'maggiore': 'mah-JOH-reh',
    'maggiori': 'mah-JOH-ree',
    'malato': 'mah-LAH-toh',
    'malata': 'mah-LAH-tah',
    'malati': 'mah-LAH-tee',
    'malate': 'mah-LAH-teh',
    'migliore': 'mee-LYOH-reh',
    'migliori': 'mee-LYOH-ree',
    'miglior': 'mee-LYOHR',
    'minimo': 'MEE-nee-moh',
    'minima': 'MEE-nee-mah',
    'minimi': 'MEE-nee-mee',
    'necessario': 'neh-ches-SAH-ryoh',
    'necessaria': 'neh-ches-SAH-ryah',
    'necessarie': 'neh-ches-SAH-ryeh',
    'necessari': 'neh-ches-SAH-ryee',
    'nero': 'NEH-roh',
    'neri': 'NEH-ree',
    'nera': 'NEH-rah',
    'nere': 'NEH-reh',
    'nervoso': 'nehr-VOH-zoh',
    'nervosa': 'nehr-VOH-zah',
    'nervosi': 'nehr-VOH-zee',
    'nervose': 'nehr-VOH-zeh',
    'noioso': 'noh-YOH-zoh',
    'noiosa': 'noh-YOH-zah',
    'noiose': 'noh-YOH-zeh',
    'noiosi': 'noh-YOH-zee',
    'noiosissimo': 'noh-yoh-ZEES-see-moh',
    'onesto': 'oh-NEH-stoh',
    'onesta': 'oh-NEH-stah',
    'oneste': 'oh-NEH-steh',
    'onesti': 'oh-NEH-stee',
    'orgoglioso': 'or-gohl-YOH-zoh',
    'orgogliosa': 'or-gohl-YOH-zah',
    'orgogliosi': 'or-gohl-YOH-zee',
    'orgogliose': 'or-gohl-YOH-zeh',
    'pazzo': 'PAHT-tsoh',
    'pazza': 'PAHT-tsah',
    'pazzi': 'PAHT-tsee',
    'pazze': 'PAHT-tseh',
    'perfetto': 'pehr-FEHT-toh',
    'perfetta': 'pehr-FEHT-tah',
    'perfetti': 'pehr-FEHT-tee',
    'perfette': 'pehr-FEHT-teh',
    'pericoloso': 'peh-ree-koh-LOH-zoh',
    'pericolosa': 'peh-ree-koh-LOH-zah',
    'pericolosi': 'peh-ree-koh-LOH-zee',
    'pericolose': 'peh-ree-koh-LOH-zeh',
    'piccolo': 'PEEK-koh-loh',
    'piccola': 'PEEK-koh-lah',
    'piccoli': 'PEEK-koh-lee',
    'piccole': 'PEEK-koh-leh',
    'piccolissimo': 'peek-koh-LEE-see-moh',
    'pieno': 'PYAY-noh',
    'piena': 'PYAY-nah',
    'piene': 'PYAY-neh',
    'pieni': 'PYAY-nee',
    'pigro': 'PEE-groh',
    'pigra': 'PEE-grah',
    'popolare': 'poh-poh-LAH-reh',
    'popolari': 'poh-poh-LAH-ree',
    'possibile': 'poh-SEE-bee-leh',
    'possibili': 'poh-SEE-bee-lee',
    'povero': 'POH-veh-roh',
    'povera': 'POH-veh-rah',
    'poveri': 'POH-veh-ree',
    'povere': 'POH-veh-reh',
    "pover'": 'POH-vehr',
    'preferito': 'preh-feh-REE-toh',
    'preferita': 'preh-feh-REE-tah',
    'preferiti': 'preh-feh-REE-tee',
    'preferite': 'preh-feh-REE-teh',
    'preoccupato': 'preh-ohk-koo-PAH-toh',
    'preoccupata': 'preh-ohk-koo-PAH-tah',
    'preoccupati': 'preh-ohk-koo-PAH-tee',
    'preoccupate': 'preh-ohk-koo-PAH-teh',
    'pronto': 'PROHN-toh',
    'pronta': 'PROHN-tah',
    'pronti': 'PROHN-tee',
    'pronte': 'PROHN-teh',
    'prossima': 'PROHS-see-mah',
    'prossimo': 'PROHS-see-moh',
    'prossime': 'PROHS-see-meh',
    'prossimi': 'PROHS-see-mee',
    'pulita': 'poo-LEE-tah',
    'pulite': 'poo-LEE-teh',
    'pulito': 'poo-LEE-toh',
    'puliti': 'poo-LEE-tee',
    'ricco': 'REEK-koh',
    'ricca': 'REEK-kah',
    'ricchi': 'REEK-kee',
    'ricche': 'REEK-keh',
    'rosso': 'ROHS-soh',
    'rossa': 'ROHS-sah',
    'rosse': 'ROHS-seh',
    'rossi': 'ROHS-see',
    'sbagliato': 'zbahl-YAH-toh',
    'sbagliata': 'zbahl-YAH-tah',
    'sbagliate': 'zbahl-YAH-teh',
    'seconda': 'seh-KOHN-dah',
    'secondo': 'seh-KOHN-doh',
    'semplice': 'SEHM-plee-cheh',
    'semplici': 'SEHM-plee-chee',
    'semplicissimi': 'sehm-plee-CHEE-see-mee',
    'serio': 'SEH-ryoh',
    'seria': 'SEH-ryah',
    'seri': 'SEH-ree',
    'serie': 'SEH-ryeh',
    'stessa': 'STEHS-sah',
    'stesso': 'STEHS-soh',
    'stessi': 'STEHS-see',
    'stesse': 'STEHS-seh',
    'straniera': 'strah-NYAY-rah',
    'straniere': 'strah-NYAY-reh',
    'straniero': 'strah-NYAY-roh',
    'stranieri': 'strah-NYAY-ree',
    'strano': 'STRAH-noh',
    'strana': 'STRAH-nah',
    'strane': 'STRAH-neh',
    'strani': 'STRAH-nee',
    'stupido': 'STOO-pee-doh',
    'stupida': 'STOO-pee-dah',
    'stupide': 'STOO-pee-deh',
    'stupidi': 'STOO-pee-dee',
    'superiori': 'soo-peh-ree-OH-ree',
    'superiore': 'soo-peh-ree-OH-reh',
    'tale': 'TAH-leh',
    'tedesco': 'teh-DEHS-koh',
    'tedesca': 'teh-DEHS-kah',
    'tedesche': 'teh-DEHS-keh',
    'tedeschi': 'teh-DEHS-kee',
    'terribile': 'tehr-REE-bee-leh',
    'terribili': 'tehr-REE-bee-lee',
    'timido': 'TEE-mee-doh',
    'timida': 'TEE-mee-dah',
    'timide': 'TEE-mee-deh',
    'timidi': 'TEE-mee-dee',
    'triste': 'TREE-steh',
    'tristi': 'TREE-stee',
    'ubriaco': 'oo-bree-AH-koh',
    'ubriaca': 'oo-bree-AH-kah',
    'ubriachi': 'oo-bree-AH-kee',
    'ubriache': 'oo-bree-AH-keh',
    'ultima': 'OOL-tee-mah',
    'ultimo': 'OOL-tee-moh',
    'ultimi': 'OOL-tee-mee',
    'ultime': 'OOL-tee-meh',
    'umano': 'oo-MAH-noh',
    'umani': 'oo-MAH-nee',
    'umana': 'oo-MAH-nah',
    'umane': 'oo-MAH-neh',
    'unica': 'OO-nee-kah',
    'unico': 'OO-nee-koh',
    'uniche': 'OO-nee-keh',
    'unici': 'OO-nee-chee',
    'vecchio': 'VEHK-kyoh',
    'vecchia': 'VEHK-kyah',
    'vecchi': 'VEHK-kee',
    'vecchie': 'VEHK-kyeh',
    'veloce': 'veh-LOH-cheh',
    'veloci': 'veh-LOH-chee',
    'vicina': 'vee-CHEE-nah',
    'vicino': 'vee-CHEE-noh',
    'vicini': 'vee-CHEE-nee',
    'vicine': 'vee-CHEE-neh',
    'vicinissime': 'vee-chee-NEES-see-meh',
    'vivo': 'VEE-voh',
    'viva': 'VEE-vah',
    'vivi': 'VEE-vee',
    'vive': 'VEE-veh',
}


def parse_feats(feats):
    data = {}
    if isinstance(feats, str):
        for part in feats.split('|'):
            if '=' in part:
                key, value = part.split('=', 1)
                data[key] = value
    return data


def build_note(feats, gendered):
    gender_note = None
    gender = feats.get('Gender')
    number = feats.get('Number')
    if gendered and gender == 'Masc':
        gender_note = 'masculine'
    elif gendered and gender == 'Fem':
        gender_note = 'feminine'
    if number == 'Plur':
        if gender_note:
            gender_note = f'{gender_note} plural'
        else:
            gender_note = 'plural'
    return gender_note or ''


base_path = Path('vocabulary/dataframes/ADJ')

for lemma, senses in lemma_senses.items():
    path = base_path / f'{lemma}.tsv'
    df = pd.read_csv(path, sep='\t')
    genders = set()
    for feats in df['feats']:
        gender = parse_feats(feats).get('Gender')
        if gender in {'Masc', 'Fem'}:
            genders.add(gender)
    gendered = len(genders) > 1
    specials = special_translations

    def translate(row):
        text = row['text']
        if text in specials:
            return specials[text]
        feats = parse_feats(row['feats'])
        note = build_note(feats, gendered)
        if note:
            return f"{senses} ({note})"
        return senses

    df['translation_en'] = df.apply(translate, axis=1)
    missing = set(df['text']) - set(pronunciations)
    if missing:
        raise ValueError(f'Missing pronunciations for {lemma}: {sorted(missing)}')
    df['pronunciation'] = df['text'].map(pronunciations)
    df.to_csv(path, sep='\t', index=False)
