#!/usr/bin/env python3
import csv
import os

ENTRIES = {
    'amabile': ('ah-MAH-bee-leh', 'lovable; amiable'),
    'amato': ('ah-MAH-toh', 'beloved; dear (masculine)'),
    'amari': ('ah-MAH-ree', 'bitter (masculine plural)'),
    'amaro': ('ah-MAH-roh', 'bitter (masculine)'),
    'amara': ('ah-MAH-rah', 'bitter (feminine)'),
    'amata': ('ah-MAH-tah', 'beloved; dear (feminine)'),
    'amati': ('ah-MAH-tee', 'beloved; dear (masculine plural)'),
    'amazzonica': ('ah-mahts-ZOH-nee-kah', 'Amazonian (feminine)'),
    'ambidestro': ('ahm-bee-DEH-stroh', 'ambidextrous (masculine)'),
    'ambidestra': ('ahm-bee-DEH-strah', 'ambidextrous (feminine)'),
    'ambientale': ('ahm-byehn-TAH-leh', 'environmental'),
    'ambiguo': ('ahm-BEE-gwoh', 'ambiguous (masculine)'),
    'ambigua': ('ahm-BEE-gwah', 'ambiguous (feminine)'),
    'ambigue': ('ahm-BEE-gweh', 'ambiguous (feminine plural)'),
    'ambizioso': ('ahm-bee-TSEE-OH-zoh', 'ambitious (masculine)'),
    'ambiziosa': ('ahm-bee-TSEE-OH-zah', 'ambitious (feminine)'),
    'ambiziosi': ('ahm-bee-TSEE-OH-zee', 'ambitious (masculine plural)'),
    'ambiziose': ('ahm-bee-TSEE-OH-zeh', 'ambitious (feminine plural)'),
    'ambulante': ('ahm-boo-LAHN-teh', 'traveling; itinerant'),
    'americana': ('ah-meh-rah-KAH-nah', 'American (feminine)'),
    'americani': ('ah-meh-rah-KAH-nee', 'American (masculine plural)'),
    'americane': ('ah-meh-rah-KAH-neh', 'American (feminine plural)'),
    'americano': ('ah-meh-rah-KAH-noh', 'American (masculine)'),
    'amiche': ('ah-MEE-keh', 'friends (feminine plural)'),
    'amichevole': ('ah-mee-keh-VOH-leh', 'friendly'),
    'amichevoli': ('ah-mee-keh-VOH-lee', 'friendly (plural)'),
    'amici': ('ah-MEE-chee', 'friends (masculine plural)'),
    'ammalato': ('ahm-mah-LAH-toh', 'sick; ill (masculine)'),
    'ammalata': ('ahm-mah-LAH-tah', 'sick; ill (feminine)'),
    'ammalati': ('ahm-mah-LAH-tee', 'sick; ill (masculine plural)'),
    'ammalate': ('ahm-mah-LAH-teh', 'sick; ill (feminine plural)'),
    'amministrative': ('ahm-mee-nees-trah-TEE-veh', 'administrative (feminine plural)'),
    'ammirabile': ('ahm-mee-RAH-bee-leh', 'admirable'),
    'ammirevole': ('ahm-mee-REH-voh-leh', 'praiseworthy; admirable'),
    'ammuffito': ('ahm-moof-FEE-toh', 'moldy (masculine)'),
    'ammutolito': ('ahm-moo-toh-LEE-toh', 'speechless (masculine)'),
    'amorale': ('ah-moh-RAH-leh', 'amoral'),
    'amorosa': ('ah-moh-ROH-zah', 'loving; romantic (feminine)'),
    'ampio': ('AHM-pyoh', 'wide; spacious (masculine)'),
    'ampia': ('AHM-pyah', 'wide; spacious (feminine)'),
    'anacronistico': ('ah-nah-kroh-NEES-tee-skoh', 'anachronistic'),
    'analcolica': ('ah-nahl-KOH-lee-kah', 'nonalcoholic (feminine)'),
    'analcoliche': ('ah-nahl-KOH-lee-keh', 'nonalcoholic (feminine plural)'),
    'analfabeta': ('ah-nahl-fah-BEH-tah', 'illiterate (feminine)'),
    'analfabete': ('ah-nahl-fah-BEH-teh', 'illiterate (feminine plural)'),
    'analfabeti': ('ah-nahl-fah-BEH-tee', 'illiterate (masculine plural)'),
    'analgesici': ('ah-nahl-JEH-zee-chee', 'analgesic (masculine plural)'),
    'analoga': ('ah-NAH-loh-gah', 'analogous (feminine)'),
    'analogo': ('ah-NAH-loh-goh', 'analogous (masculine)'),
    'anatomica': ('ah-nah-TOH-mee-kah', 'anatomical (feminine)'),
    'ancestrale': ('ahn-cheh-STRAH-leh', 'ancestral; ancient'),
    'anchilosati': ('ahn-kee-loh-ZAH-tee', 'stiff; ankylosed (masculine plural)'),
    'andaluso': ('ahn-dah-LOO-zoh', 'Andalusian (masculine)'),
    'andalusa': ('ahn-dah-LOO-zah', 'Andalusian (feminine)'),
    'andalusi': ('ahn-dah-LOO-zee', 'Andalusian (masculine plural)'),
    'andaluse': ('ahn-dah-LOO-zeh', 'Andalusian (feminine plural)'),
    'androfobica': ('ahn-droh-FOH-bee-kah', 'androphobic (feminine)'),
    'anemico': ('ah-NEH-mee-koh', 'anemic (masculine)'),
    'anemica': ('ah-NEH-mee-kah', 'anemic (feminine)'),
    'anglosassone': ('ahn-gloh-SAH-soh-neh', 'Anglo-Saxon'),
    'angusto': ('ahn-GOO-stoh', 'narrow; cramped (masculine)'),
    'angusti': ('ahn-GOO-stee', 'narrow; cramped (masculine plural)'),
    'animale': ('ah-nee-MAH-leh', 'animal; animal-like'),
    'animali': ('ah-nee-MAH-lee', 'animal; animal-like (plural)'),
    'animato': ('ah-nee-MAH-toh', 'animated; lively (masculine)'),
    'animata': ('ah-nee-MAH-tah', 'animated; lively (feminine)'),
    'animati': ('ah-nee-MAH-tee', 'animated; lively (masculine plural)'),
    'animoso': ('ah-nee-MOH-zoh', 'spirited; courageous (masculine)'),
    'annegato': ('ahn-neh-GAH-toh', 'drowned (masculine)'),
    'annoiato': ('ahn-noy-YAH-toh', 'bored (masculine)'),
    'annoiata': ('ahn-noy-YAH-tah', 'bored (feminine)'),
    'annoiati': ('ahn-noy-YAH-tee', 'bored (masculine plural)'),
    'annoiate': ('ahn-noy-YAH-teh', 'bored (feminine plural)'),
    'annuale': ('ahn-noo-AH-leh', 'annual'),
    'annuali': ('ahn-noo-AH-lee', 'annual (plural)'),
    'annui': ('AHN-noo-ee', 'annual; yearly (masculine plural)'),
    'anomala': ('ah-NOH-mah-lah', 'anomalous (feminine)'),
    'anonimo': ('ah-NOH-nee-moh', 'anonymous (masculine)'),
    'anonima': ('ah-NOH-nee-mah', 'anonymous (feminine)'),
    'anonimi': ('ah-NOH-nee-mee', 'anonymous (masculine plural)'),
    'ansioso': ('ahn-SYOH-zoh', 'anxious (masculine)'),
    'ansiosa': ('ahn-SYOH-zah', 'anxious (feminine)'),
    'ansiosi': ('ahn-SYOH-zee', 'anxious (masculine plural)'),
    'ansiose': ('ahn-SYOH-zeh', 'anxious (feminine plural)'),
    'antartico': ('ahn-TAR-tee-koh', 'Antarctic'),
    'anteriore': ('ahn-teh-ree-OH-reh', 'anterior; front'),
    'anti': ('AHN-tee', 'anti; against'),
    'antiaderente': ('ahn-tee-ah-deh-REN-teh', 'nonstick'),
    'antica': ('ahn-TEE-kah', 'ancient; old (feminine)'),
    'antiche': ('ahn-TEE-keh', 'ancient; old (feminine plural)'),
    'antichi': ('ahn-TEE-kee', 'ancient; old (masculine plural)'),
    'anticipata': ('ahn-tee-chee-PAH-tah', 'early; anticipated (feminine)'),
    'antico': ('ahn-TEE-koh', 'ancient; old (masculine)'),
    'antincendio': ('ahn-teen-CHEN-dyoh', 'fireproof; fire-fighting'),
    'antipatico': ('ahn-tee-PAH-tee-koh', 'unpleasant; annoying (masculine)'),
    'antipatici': ('ahn-tee-PAH-tee-chee', 'unpleasant; annoying (masculine plural)'),
    'antipatiche': ('ahn-tee-PAH-tee-keh', 'unpleasant; annoying (feminine plural)'),
    'antiquato': ('ahn-tee-KWAH-toh', 'old-fashioned; outdated (masculine)'),
    'antitraspirante': ('ahn-tee-trahs-pee-RAHN-teh', 'antiperspirant'),
    'anziano': ('ahn-ZYAH-noh', 'elderly; old (masculine)'),
    'anziana': ('ahn-ZYAH-nah', 'elderly; old (feminine)'),
    'anziani': ('ahn-ZYAH-nee', 'elderly; old (masculine plural)'),
    'anziane': ('ahn-ZYAH-neh', 'elderly; old (feminine plural)'),
    'apatica': ('ah-PAH-tee-kah', 'apathetic (feminine)'),
    'apatico': ('ah-PAH-tee-koh', 'apathetic (masculine)'),
    'aperta': ('ah-PEHR-tah', 'open (feminine)'),
    'aperte': ('ah-PEHR-teh', 'open (feminine plural)'),
    'aperti': ('ah-PEHR-tee', 'open (masculine plural)'),
    'aperto': ('ah-PEHR-toh', 'open (masculine)'),
    'apparente': ('ahp-pah-REHN-teh', 'apparent'),
    'appariscente': ('ahp-pah-ree-SHEHN-teh', 'flashy; showy'),
    'appariscenti': ('ahp-pah-ree-SHEHN-tee', 'flashy; showy (plural)'),
    'appassionante': ('ahp-pah-syo-NAHN-teh', 'exciting; enthralling'),
    'appassionato': ('ahp-pah-syo-NAH-toh', 'passionate (masculine)'),
    'appassionata': ('ahp-pah-syo-NAH-tah', 'passionate (feminine)'),
    'appassionate': ('ahp-pah-syo-NAH-teh', 'passionate (feminine plural)'),
    'appassiti': ('ahp-pah-SEE-tee', 'wilted; withered (masculine plural)'),
    'appetitoso': ('ahp-peh-tee-TOH-zoh', 'appetizing; tasty (masculine)'),
    'appiccicaticcia': ('ahp-pee-chee-kah-TEE-chah', 'sticky (feminine)'),
    'appiccicaticcio': ('ahp-pee-chee-kah-TEE-choh', 'sticky (masculine)'),
    'appiccicoso': ('ahp-pee-chee-KOH-zoh', 'sticky; clingy (masculine)'),
    'appiccicosa': ('ahp-pee-chee-KOH-zah', 'sticky; clingy (feminine)'),
    'appicicoso': ('ahp-pee-chee-KOH-zoh', 'sticky; clingy (masculine)'),
    'applicabile': ('ahp-lee-KAH-bee-leh', 'applicable'),
    'apprezzati': ('ahp-prehts-AH-tee', 'appreciated; valued (masculine plural)'),
    'approfondita': ('ahp-proh-foon-DEE-tah', 'in-depth; thorough (feminine)'),
    'appropriato': ('ahp-proh-pree-AH-toh', 'appropriate; suitable (masculine)'),
    'appropriata': ('ahp-proh-pree-AH-tah', 'appropriate; suitable (feminine)'),
    'appropriati': ('ahp-proh-pree-AH-tee', 'appropriate; suitable (masculine plural)'),
    'approssimativo': ('ahp-proh-see-mah-TEE-voh', 'approximate; rough (masculine)'),
    'approssimativa': ('ahp-proh-see-mah-TEE-vah', 'approximate; rough (feminine)'),
    'appuntito': ('ahp-poon-TEE-toh', 'pointed; sharp (masculine)'),
    'appuntita': ('ahp-poon-TEE-tah', 'pointed; sharp (feminine)'),
    'appuntite': ('ahp-poon-TEE-teh', 'pointed; sharp (feminine plural)'),
    'arabico': ('ah-RAH-bee-koh', 'Arabic'),
    'arabo': ('AH-rah-boh', 'Arab (masculine)'),
    'araba': ('AH-rah-bah', 'Arab (feminine)'),
    'arabi': ('AH-rah-bee', 'Arab (masculine plural)'),
    'arabe': ('AH-rah-beh', 'Arab (feminine plural)'),
    'arancione': ('ah-rahn-CHOH-neh', 'orange'),
    'arancioni': ('ah-rahn-CHOH-nee', 'orange (plural)'),
    'arbitrarie': ('ahr-bee-TRAH-ryeh', 'arbitrary (feminine plural)'),
    'archeologici': ('ahr-keh-oh-LOH-jee-chee', 'archaeological (masculine plural)'),
    'arcicontento': ('ahr-chee-kon-TEN-toh', 'overjoyed; thrilled (masculine)'),
    'ardente': ('ahr-DEN-teh', 'burning; passionate'),
    'argenteo': ('ahr-JEN-teh-oh', 'silvery'),
    'argentino': ('ahr-jen-TEE-noh', 'Argentinian (masculine)'),
    'argentina': ('ahr-jen-TEE-nah', 'Argentinian (feminine)'),
    'argentini': ('ahr-jen-TEE-nee', 'Argentinian (masculine plural)'),
    'argentine': ('ahr-jen-TEE-neh', 'Argentinian (feminine plural)'),
    'arguto': ('ahr-GOO-toh', 'sharp-witted; shrewd (masculine)'),
    'arguta': ('ahr-GOO-tah', 'sharp-witted; shrewd (feminine)'),
    'aristocratico': ('ah-ree-stoh-KRAH-tee-koh', 'aristocratic'),
    'armato': ('ahr-MAH-toh', 'armed (masculine)'),
    'armata': ('ahr-MAH-tah', 'armed (feminine)'),
    'armate': ('ahr-MAH-teh', 'armed (feminine plural)'),
    'arrabbiato': ('ahr-rahb-BYAH-toh', 'angry (masculine)'),
    'arrabbiata': ('ahr-rahb-BYAH-tah', 'angry (feminine)'),
    'arrabbiati': ('ahr-rahb-BYAH-tee', 'angry (masculine plural)'),
    'arrabbiate': ('ahr-rahb-BYAH-teh', 'angry (feminine plural)'),
    'arrapato': ('ahr-rah-PAH-toh', 'horny; aroused (masculine)'),
    'arrivati​​': ('ahr-ree-VAH-tee', 'arrived (masculine plural)'),
    'arrogante': ('ahr-roh-GAHN-teh', 'arrogant'),
    'arroganti': ('ahr-roh-GAHN-tee', 'arrogant (plural)'),
    'arrossito': ('ahr-roh-SEE-toh', 'blushing; flushed (masculine)'),
    'arrosto': ('ahr-ROH-stoh', 'roasted; roast'),
    'arrrabbiate': ('ahr-rahb-BYAH-teh', 'angry (feminine plural)'),
    'arrugginito': ('ahr-rood-jee-NEE-toh', 'rusty (masculine)'),
    'artico': ('AHR-tee-koh', 'Arctic (masculine)'),
    'artica': ('AHR-tee-kah', 'Arctic (feminine)'),
    'articolato': ('ahr-tee-koh-LAH-toh', 'articulate; articulated (masculine)'),
    'artificiale': ('ahr-tee-fee-CHAH-leh', 'artificial'),
    'artificiali': ('ahr-tee-fee-CHAH-lee', 'artificial (plural)'),
    'artistico': ('ahr-TEE-stee-koh', 'artistic (masculine)'),
    'artistica': ('ahr-TEE-stee-kah', 'artistic (feminine)'),
    'asciutto': ('ah-SHOO-toh', 'dry (masculine)'),
    'asciutti': ('ah-SHOO-tee', 'dry (masculine plural)'),
    'asciutte': ('ah-SHOO-teh', 'dry (feminine plural)'),
    'asiatico': ('ah-zhee-AH-tee-koh', 'Asian (masculine)'),
    'asiatici': ('ah-zhee-AH-tee-chee', 'Asian (masculine plural)'),
    'asiatica': ('ah-zhee-AH-tee-kah', 'Asian (feminine)'),
    'asiatiche': ('ah-zhee-AH-tee-keh', 'Asian (feminine plural)'),
    'asociale': ('ah-soh-CHAH-leh', 'antisocial'),
    'aspiranti': ('ahs-pee-RAHN-tee', 'aspiring; would-be (plural)'),
    'aspri': ('AHS-pree', 'harsh; rough (masculine plural)'),
    'aspra': ('AHS-prah', 'harsh; rough (feminine)'),
    'aspre': ('AHS-preh', 'harsh; rough (feminine plural)'),
    'assassino': ('ahs-sah-SEE-noh', 'murderous; killer (masculine)'),
    'assediata': ('ahs-seh-DYAH-tah', 'besieged (feminine)'),
    'assegnati': ('ahs-sehn-YAH-tee', 'assigned (masculine plural)'),
    'assente': ('ahs-SEHN-teh', 'absent'),
    'assenti': ('ahs-SEHN-tee', 'absent (plural)'),
    'assetato': ('ahs-seh-TAH-toh', 'thirsty (masculine)'),
    'assetata': ('ahs-seh-TAH-tah', 'thirsty (feminine)'),
    'assetati': ('ahs-seh-TAH-tee', 'thirsty (masculine plural)'),
    'assetate': ('ahs-seh-TAH-teh', 'thirsty (feminine plural)'),
    'assicurativa': ('ahs-see-koo-rah-TEE-vah', 'insurance (feminine)'),
    'assillante': ('ahs-seel-LAHN-teh', 'nagging; harassing'),
    'assimilabili': ('ahs-see-mee-LAH-bee-lee', 'comparable; assimilable (plural)'),
    'assoluto': ('ahs-soh-LOO-toh', 'absolute (masculine)'),
    'assoluta': ('ahs-soh-LOO-tah', 'absolute (feminine)'),
    'assomigliante': ('ahs-soh-mee-LYAHN-teh', 'resembling; similar'),
    'assonnato': ('ahs-sohn-NAH-toh', 'sleepy (masculine)'),
    'assonnata': ('ahs-sohn-NAH-tah', 'sleepy (feminine)'),
    'assortita': ('ahs-sohr-TEE-tah', 'assorted; mixed (feminine)'),
    'assortiti': ('ahs-sohr-TEE-tee', 'assorted; mixed (masculine plural)'),
    'assorta': ('ahs-SOHR-tah', 'absorbed; engrossed (feminine)'),
    'assurdo': ('ahs-SOOR-doh', 'absurd; ridiculous (masculine)'),
    'assurda': ('ahs-SOOR-dah', 'absurd; ridiculous (feminine)'),
    'assurde': ('ahs-SOOR-deh', 'absurd; ridiculous (feminine plural)'),
    'assurdi': ('ahs-SOOR-dee', 'absurd; ridiculous (masculine plural)'),
    'astemio': ('ahs-TEH-myoh', 'teetotal; abstinent (masculine)'),
    'astratta': ('ahs-TRAH-tah', 'abstract (feminine)'),
    'astuto': ('ahs-TOO-toh', 'cunning; clever (masculine)'),
    'ateniese': ('ah-teh-NYEH-seh', 'Athenian'),
    'atea': ('AH-teh-ah', 'atheist (feminine)'),
    'ateo': ('AH-teh-oh', 'atheist (masculine)'),
    'atlantiche': ('aht-LAHN-tee-keh', 'Atlantic (feminine plural)'),
    'atletica': ('ah-TLEH-tee-kah', 'athletic (feminine)'),
    'atletico': ('ah-TLEH-tee-koh', 'athletic (masculine)'),
    'atmosferico': ('aht-mohs-FEH-ree-koh', 'atmospheric'),
    'atomico': ('ah-TOH-mee-koh', 'atomic (masculine)'),
    'atomica': ('ah-TOH-mee-kah', 'atomic (feminine)'),
    'atomici': ('ah-TOH-mee-chee', 'atomic (masculine plural)'),
    'atroce': ('ah-TROH-cheh', 'atrocious; cruel'),
    'attendibile': ('ah-ten-DEE-bee-leh', 'reliable; trustworthy'),
    'attendibili': ('ah-ten-DEE-bee-lee', 'reliable; trustworthy (plural)'),
    'attento': ('ah-TEN-toh', 'attentive; careful (masculine)'),
    'attenta': ('ah-TEN-tah', 'attentive; careful (feminine)'),
    'attenti': ('ah-TEN-tee', 'attentive; careful (masculine plural)'),
    'attente': ('ah-TEN-teh', 'attentive; careful (feminine plural)'),
    'attenziane': ('ah-ten-TSYAH-neh', 'attentive; careful (feminine plural)'),
    'atterrito': ('ah-tehr-REE-toh', 'terrified (masculine)'),
    'attesi': ('ah-TEH-zee', 'awaited; expected (masculine plural)'),
    'attiguo': ('ah-TEE-gwoh', 'adjacent; adjoining (masculine)'),
    'attillati': ('ah-tee-LAH-tee', 'tight-fitting (masculine plural)'),
    'attivo': ('ah-TEE-voh', 'active (masculine)'),
    'attiva': ('ah-TEE-vah', 'active (feminine)'),
    'attivi': ('ah-TEE-vee', 'active (masculine plural)'),
    'attive': ('ah-TEE-veh', 'active (feminine plural)'),
    'attraente': ('ah-trah-EHN-teh', 'attractive'),
    'attrici': ('ah-TREE-chee', 'actresses (feminine plural)'),
    'attuale': ('ah-TWAH-leh', 'current; present'),
    'attuali': ('ah-TWAH-lee', 'current; present (plural)'),
}

ROOT = 'vocabulary/dataframes/ADJ'
FILES = sorted([
    name for name in os.listdir(ROOT)
    if name.lower().startswith(('am', 'an', 'ao', 'ap', 'aq', 'ar', 'as', 'at'))
])

def main():
    for fname in FILES:
        path = os.path.join(ROOT, fname)
        with open(path, newline='', encoding='utf-8') as rf:
            reader = csv.DictReader(rf, delimiter='\t')
            rows = list(reader)
            fieldnames = reader.fieldnames
        updated = False
        for row in rows:
            text = row['text']
            if text not in ENTRIES:
                raise KeyError(f"Missing entry for {text}")
            pron, trans = ENTRIES[text]
            if row['pronunciation'] != pron or row['translation_en'] != trans:
                row['pronunciation'] = pron
                row['translation_en'] = trans
                updated = True
        if updated:
            with open(path, 'w', newline='', encoding='utf-8') as wf:
                writer = csv.DictWriter(wf, fieldnames=fieldnames, delimiter='\t')
                writer.writeheader()
                writer.writerows(rows)

if __name__ == '__main__':
    main()
