import csv
from pathlib import Path

entries = {
    'rabbia': ('RAHB-byah', 'anger; rage'),
    'rabbino': ('rahb-BEE-noh', 'rabbi'),
    'racchetta': ('rahk-KEHT-tah', 'racket'),
    'racchette': ('rahk-KEHT-teh', 'rackets'),
    'raccoglitore': ('rahk-koh-lyee-TOH-reh', 'binder; file folder'),
    'raccoglitori': ('rahk-koh-lyee-TOH-ree', 'binders; file folders'),
    'raccolta': ('rahk-KOHL-tah', 'collection'),
    'raccolte': ('rahk-KOHL-teh', 'collections'),
    'raccolti': ('rahk-KOHL-tee', 'crops; harvests'),
    'raccolto': ('rahk-KOHL-toh', 'harvest; crop'),
    'raccomandazione': ('rahk-koh-mahn-dah-TSYOH-neh', 'recommendation; reference'),
    'racconti': ('rahk-KOHN-tee', 'stories; tales'),
    'racconto': ('rahk-KOHN-toh', 'story; tale'),
    'raccordo': ('rahk-KOHR-doh', 'junction; connector'),
    'radar': ('RAH-dahr', 'radar'),
    'radiazioni': ('rah-dyah-TSYOH-nee', 'radiations'),
    'radicale': ('rah-dee-KAH-leh', 'radical'),
    'radice': ('rah-DEE-cheh', 'root'),
    'radici': ('rah-DEE-chee', 'roots'),
    'radioamatore': ('rah-dyoh-ah-mah-TOH-reh', 'ham radio operator'),
    'radioattività': ('rah-dyoh-aht-tee-vee-TAH', 'radioactivity'),
    'radiosità': ('rah-dyoh-see-TAH', 'radiance'),
    'rado': ('RAH-doh', 'seldom'),
    'radon': ('RAH-dohn', 'radon'),
    'raffica': ('RAHF-fee-kah', 'gust; burst'),
    'rafforzamento': ('rahf-for-tsah-MEN-toh', 'strengthening; reinforcement'),
    'raffredore': ('rahf-freh-DOH-reh', 'cold; head cold'),
    'ragazzaccio': ('rah-gahts-ZAH-choh', 'bad kid; punk'),
    'ragazzina': ('rah-gahts-SEE-nah', 'little girl'),
    'ragazzine': ('rah-gahts-SEE-neh', 'little girls'),
    'ragazzone': ('rah-gahts-SOH-neh', 'big guy; big lad'),
    'raggi': ('RAH-jee', 'rays; beams'),
    'raggio': ('RAH-joh', 'ray; radius'),
    'raggiungimento': ('rahj-joon-jee-MEN-toh', 'achievement; attainment'),
    'raggruppamenti': ('rahg-groop-pah-MEN-tee', 'groupings; clusters'),
    'ragionamenti': ('rah-joh-nah-MEN-tee', 'lines of reasoning; arguments'),
    'ragionamento': ('rah-joh-nah-MEN-toh', 'reasoning; argument'),
    'ragioniere': ('rah-joh-NYAY-reh', 'accountant'),
    'ragnatela': ('rah-nyah-TAY-lah', 'spiderweb'),
    'ragni': ('RAH-nyee', 'spiders'),
    'ragno': ('RAH-nyoh', 'spider'),
    'rame': ('RAH-meh', 'copper'),
    'rami': ('RAH-mee', 'branches'),
    'rammarici': ('rahm-MAH-ree-chee', 'regrets'),
    'rammarico': ('rahm-MAH-ree-koh', 'regret; remorse'),
    'ramo': ('RAH-moh', 'branch'),
    'rana': ('RAH-nah', 'frog'),
    'ranch': ('RANCH', 'ranch'),
    'rane': ('RAH-neh', 'frogs'),
    'rango': ('RAHN-goh', 'rank; status'),
    'rap': ('RAP', 'rap'),
    'rap.': ('RAP', 'rap song'),
    'rapace': ('rah-PAH-cheh', 'bird of prey; predator'),
    'rapimento': ('rah-pee-MEN-toh', 'kidnapping; abduction'),
    'rapina': ('rah-PEE-nah', 'robbery'),
    'rapinatore': ('rah-pee-nah-TOH-reh', 'robber'),
    'rapitori': ('rah-pee-TOH-ree', 'kidnappers'),
    'rapper': ('RAP-per', 'rapper'),
    'rappresentante': ('rahp-preh-zen-TAHN-teh', 'representative'),
    'rappresentanti': ('rahp-preh-zen-TAHN-tee', 'representatives'),
    'rappresentazione': ('rahp-preh-zen-tah-TSYOH-neh', 'representation; performance'),
    'rarità': ('rah-ree-TAH', 'rarity'),
    'rasatura': ('rah-sah-TOO-rah', 'shaving; shave'),
    'raschiatura': ('rah-skee-ah-TOO-rah', 'scraping; abrasion'),
    'rasoio': ('rah-ZOH-yoh', 'razor'),
    'ratti': ('RAHT-tee', 'rats'),
    'ratto': ('RAHT-toh', 'rat'),
    'rauchi': ('ROW-kee', 'hoarse people'),
    'rauco': ('ROW-koh', 'hoarse (voice)'),
    'ravioli': ('rah-vyoh-LEE', 'ravioli; dumplings'),
    'razza': ('RAHT-tsah', 'race; breed'),
    'razze': ('RAHT-tseh', 'races; breeds'),
    'razzi': ('RAHT-tsee', 'rockets'),
    'razzismo': ('rah-TSIZ-moh', 'racism'),
    'razzisti': ('rah-TSIS-tee', 'racists'),
    'razzo': ('RAHT-tsoh', 'rocket'),
    're': ('REH', 'king'),
    're.': ('REH', 'king'),
    'realizzazione': ('reh-ah-leed-zah-TSYOH-neh', 'realization; accomplishment'),
    'realizzazioni': ('reh-ah-leed-zah-TSYOH-nee', 'realizations; accomplishments'),
    'reati': ('reh-AH-tee', 'crimes'),
    'reato': ('reh-AH-toh', 'crime'),
    'reazione': ('reh-ah-TSYOH-neh', 'reaction'),
    'reazioni': ('reh-ah-TSYOH-nee', 'reactions'),
    'recensione': ('reh-chen-SYOH-neh', 'review'),
    'recensioni': ('reh-chen-SYOH-nee', 'reviews'),
    'recente': ('reh-CHEN-teh', 'recently'),
    'reception': ('reh-CHEHP-syon', 'reception desk; front desk'),
    'receptionist': ('reh-CHEHP-syo-neest', 'receptionist'),
    'recessione': ('reh-ches-SYOH-neh', 'recession'),
    'recinto': ('reh-CHEEN-toh', 'enclosure; pen'),
    'recinzione': ('reh-chin-TSYOH-neh', 'fence; enclosure'),
    'recipiente': ('reh-chee-PYEN-teh', 'container'),
    'recita': ('REH-chee-tah', 'performance; recital'),
    'recitazione': ('reh-chee-tah-TSYOH-neh', 'acting; recitation'),
    'recite': ('REH-chee-teh', 'performances; recitals'),
    'reclami': ('reh-KLAH-mee', 'complaints'),
    'reclamo': ('reh-KLAH-moh', 'complaint; claim'),
    'reclusione': ('reh-kloo-zyoh-NEH', 'imprisonment; confinement'),
    'recluta': ('REH-kloo-tah', 'recruit'),
    'record': ('REH-kord', 'record'),
    'recupero': ('reh-KOO-peh-roh', 'recovery; retrieval'),
    'redattore': ('reh-daht-TOH-reh', 'editor'),
    'reddito': ('REHD-dee-toh', 'income'),
    'redenzione': ('reh-den-TSYOH-neh', 'redemption'),
    'redini': ('REH-dee-nee', 'reins'),
    'referendum': ('reh-feh-REHN-doom', 'referendum'),
    'refettorio': ('reh-feht-TOH-ryoh', 'refectory; dining hall'),
    'refrigeratore': ('reh-free-jeh-rah-TOH-reh', 'refrigerator; cooler'),
    'reggae': ('REH-geh', 'reggae'),
    'reggiseno': ('reh-jee-SAY-noh', 'bra'),
    'regime': ('reh-JEE-meh', 'regime'),
    'regina': ('reh-JEE-nah', 'queen'),
    'regine': ('reh-JEE-neh', 'queens'),
    'regione': ('reh-JOH-neh', 'region'),
    'regioni': ('reh-JOH-nee', 'regions'),
    'regista': ('reh-JEES-tah', 'director'),
    'registratore': ('reh-jees-trah-TOH-reh', 'recorder'),
    'registrazione': ('reh-jees-trah-TSYOH-neh', 'recording; registration'),
    'registrazioni': ('reh-jees-trah-TSYOH-nee', 'recordings; registrations'),
    'registri': ('reh-JEES-tree', 'registers; ledgers'),
    'registro': ('reh-JEES-troh', 'register; ledger'),
    'regno': ('REH-nyoh', 'kingdom; realm'),
    'regolamenti': ('reh-goh-lah-MEN-tee', 'regulations; rulebooks'),
    'regolamento': ('reh-goh-lah-MEN-toh', 'regulation; rulebook'),
    'regolarità': ('reh-goh-lah-ree-TAH', 'regularity'),
    'reietto': ('reh-YEHT-toh', 'outcast'),
    'reincarnazione': ('reh-een-kar-nah-TSYOH-neh', 'reincarnation'),
    'reindirizzamento': ('reh-een-dee-reet-tsah-MEN-toh', 'redirection; rerouting'),
    'relatività': ('reh-lah-tee-vee-TAH', 'relativity'),
    'relazione': ('reh-lah-TSYOH-neh', 'relationship; report'),
    'relazioni': ('reh-lah-TSYOH-nee', 'relationships; reports'),
    'religione': ('reh-lee-JOH-neh', 'religion'),
    'religioni': ('reh-lee-JOH-nee', 'religions'),
    'relitto': ('reh-LEET-toh', 'wreck; wreckage'),
    'remoto': ('reh-MOH-toh', 'remote; distant'),
    'remunerazione': ('reh-moo-neh-rah-TSYOH-neh', 'remuneration; payment'),
    'rendimento': ('ren-dee-MEN-toh', 'yield; performance'),
    'rene': ('REH-neh', 'kidney'),
    'renna': ('REN-nah', 'reindeer'),
    'renne': ('REN-neh', 'reindeer (plural)'),
    'reparto': ('reh-PAR-toh', 'department; ward'),
    'reperto': ('reh-PEHR-toh', 'artifact; find'),
    'replica': ('REH-plee-kah', 'reply; replica'),
    'reporter': ('reh-POR-tehr', 'reporter'),
    'repressione': ('reh-preh-SYOH-neh', 'repression; crackdown'),
    'repubblica': ('reh-POOB-blee-kah', 'republic'),
    'repubblicana': ('reh-poob-blee-KAH-nah', 'republican (feminine)'),
    'repubblicani': ('reh-poob-blee-KAH-nee', 'republicans'),
    'repubblicano': ('reh-poob-blee-KAH-noh', 'republican'),
    'repubbliche': ('reh-POOB-blee-keh', 'republics'),
    'repulsione': ('reh-pool-SYOH-neh', 'repulsion'),
    'reputazione': ('reh-poo-tah-TSYOH-neh', 'reputation'),
    'requisito': ('reh-kwee-ZEE-toh', 'requirement'),
    'resa': ('REH-zah', 'surrender; yield'),
    'rese': ('REH-zeh', 'made'),
    'resi': ('REH-zee', 'I made'),
    'residenti': ('reh-zee-DEN-tee', 'residents'),
    'residenza': ('reh-zee-DEN-tsah', 'residence'),
    'residenze': ('reh-zee-DEN-tseh', 'residences'),
    'resistenza': ('reh-zee-STEN-tsah', 'resistance'),
    'resoconto': ('reh-zoh-KOHN-toh', 'report; account'),
    'respawn': ('ree-SPAWN', 'respawn'),
    'respiri': ('reh-SPEE-ree', 'breaths'),
    'respiro': ('reh-SPEE-roh', 'breath'),
    'respondabile': ('reh-spohn-dah-BEE-leh', 'person in charge'),
    'responsabile': ('reh-spohn-sah-BEE-leh', 'responsible person'),
    'responsabili': ('reh-spohn-sah-BEE-lee', 'responsible people'),
    'responsabilità': ('reh-spohn-sah-bee-lee-TAH', 'responsibility'),
    'resti': ('REH-stee', 'remains'),
    'resto': ('REH-stoh', 'rest; remainder'),
    'restringimento': ('reh-streen-jee-MEN-toh', 'narrowing; tightening'),
    'rete': ('REH-teh', 'net; network'),
    'reti': ('REH-tee', 'nets; networks'),
    'retina': ('reh-TEE-nah', 'retina'),
    'retribuzione': ('reh-tree-boo-TSYOH-neh', 'pay; compensation'),
    'retribuzioni': ('reh-tree-boo-TSYOH-nee', 'payments; compensations'),
    'retro': ('REH-troh', 'rear; back'),
    'retta': ('REHT-tah', 'tuition; fee'),
    'rettangolo': ('reht-TAHN-goh-loh', 'rectangle'),
    'rettili': ('REHT-tee-lee', 'reptiles'),
    'revisione': ('reh-vee-ZYOH-neh', 'revision; review'),
    'riabilitazione': ('ree-ah-bee-lee-tah-TSYOH-neh', 'rehabilitation'),
    'ribelle': ('ree-BEHL-leh', 'rebel'),
    'ribelli': ('ree-BEHL-lee', 'rebels'),
    'ribellione': ('ree-bel-lyoh-NEH', 'rebellion'),
    'ribes': ('REE-behs', 'currant'),
    'ricambio': ('ree-KAHM-byoh', 'spare part; replacement'),
    'ricatto': ('ree-KAHT-toh', 'blackmail'),
    'ricchezza': ('reek-KET-tsah', 'wealth'),
    'ricchezze': ('reek-KET-tseh', 'riches'),
    'ricchi': ('REE-kee', 'rich people'),
    'ricci': ('REE-chee', 'sea urchins'),
    'riccio': ('REE-choh', 'hedgehog; curl'),
    'ricerca': ('ree-CHEHR-kah', 'research'),
    'ricercatori': ('ree-cher-kah-TOH-ree', 'researchers (masculine)'),
    'ricercatrice': ('ree-cher-kah-TREE-cheh', 'researcher (feminine)'),
    'ricerche': ('ree-CHEHR-keh', 'research studies'),
    'ricetta': ('ree-CHEHT-tah', 'recipe'),
    'ricevimento': ('ree-chee-veh-MEN-toh', 'reception; receiving line'),
    'ricevitore': ('ree-chee-vee-TOH-reh', 'receiver'),
    'ricevuta': ('ree-cheh-VOO-tah', 'receipt'),
    'ricevute': ('ree-cheh-VOO-teh', 'receipts'),
    'richiamali': ('ree-KYAH-mah-lee', 'call them back'),
    'richiami': ('ree-KYAH-mee', 'recalls; reminders'),
    'richiamo': ('ree-KYAH-moh', 'recall; summons'),
    'richiesta': ('ree-KYEST-tah', 'request; demand'),
    'richieste': ('ree-KYEST-teh', 'requests; demands'),
    'ricompensa': ('ree-kohm-PEN-sah', 'reward'),
    'ricompense': ('ree-kohm-PEN-seh', 'rewards'),
    'riconoscimento': ('ree-koh-noh-shee-MEN-toh', 'recognition; acknowledgment'),
    'ricordi': ('ree-KOHR-dee', 'memories'),
    'ricordo': ('ree-KOHR-doh', 'memory; keepsake'),
    'ricorrenza': ('ree-kor-REN-tsah', 'anniversary; recurrence'),
    'ricorso': ('ree-KOHR-soh', 'appeal; recourse'),
    'ricostruzione': ('ree-koh-struh-TSYOH-neh', 'reconstruction'),
    'ricovero': ('ree-KOH-veh-roh', 'hospital stay; shelter'),
    'ricreazione': ('ree-kreh-ah-TSYOH-neh', 'recreation; recess'),
    'ridia': ('ree-DEE-ah', 'give it back'),
    'riduzione': ('ree-doo-TSYOH-neh', 'reduction'),
    'riferimento': ('ree-feh-ree-MEN-toh', 'reference'),
    'rifiuti': ('ree-FYOO-tee', 'waste; trash'),
    'rifiuto': ('ree-FYOO-toh', 'refusal; waste'),
    'riflessi': ('ree-FLEHS-see', 'reflections; reflexes'),
    'riflessione': ('ree-fleh-SYOH-neh', 'reflection; thought'),
    'riflesso': ('ree-FLEHS-soh', 'reflection; reflex'),
    'riforma': ('ree-FOR-mah', 'reform'),
    'riforme': ('ree-FOR-meh', 'reforms'),
    'rifornimenti': ('ree-for-nee-MEN-tee', 'supplies; provisions'),
    'rifugiati': ('ree-foo-JAH-tee', 'refugees (masculine)'),
    'rifugiato': ('ree-foo-JAH-toh', 'refugee (masculine)'),
    'rifugio': ('ree-FOO-joh', 'shelter; refuge'),
    'riga': ('REE-gah', 'line; row'),
    'righe': ('REE-geh', 'lines; rows'),
    'righelli': ('ree-GHEL-lee', 'rulers'),
    'righello': ('ree-GHEL-loh', 'ruler'),
    'rigore': ('ree-GOH-reh', 'rigor; penalty'),
    'rilievo': ('ree-LYAY-voh', 'relief; prominence'),
    'riluttanza': ('ree-loot-TAHN-tsah', 'reluctance'),
    'rima': ('REE-mah', 'rhyme'),
    'rimaste': ('ree-MAH-steh', 'stayed (feminine plural)'),
    'rimbombo': ('reem-BOHM-boh', 'rumble; boom'),
    'rimborso': ('reem-BOHR-soh', 'refund; reimbursement'),
    'rimedi': ('ree-MAY-dee', 'remedies'),
    'rimedio': ('ree-MAY-dyoh', 'remedy; cure'),
    'rimorsi': ('ree-MOHR-see', 'remorse (plural)'),
    'rimorso': ('ree-MOHR-soh', 'remorse'),
    'rimozione': ('ree-moh-TSYOH-neh', 'removal'),
    'rimpianti': ('ree-mpYAHN-tee', 'regrets'),
    'rimpianto': ('ree-mpYAHN-toh', 'regret; longing'),
    'rimuginazione': ('ree-moo-jee-nah-TSYOH-neh', 'brooding; overthinking'),
    'rinascimento': ('ree-nah-shee-MEN-toh', 'Renaissance'),
    'rinascita': ('ree-NAH-shee-tah', 'rebirth; revival'),
    'ring': ('RING', 'ring'),
    'ringhiera': ('reen-GYEH-rah', 'railing; banister'),
    'ringraziamenti': ('reen-grah-tsyah-MEN-tee', 'thanks; acknowledgments'),
    'ringraziamento': ('reen-grah-tsyah-MEN-toh', 'thank-you; gratitude'),
    'rinoceronte': ('ree-noh-cheh-ROHN-teh', 'rhinoceros'),
    'riparatore': ('ree-pah-rah-TOH-reh', 'repairman'),
    'riparazione': ('ree-pah-rah-TSYOH-neh', 'repair'),
    'riparazioni': ('ree-pah-rah-TSYOH-nee', 'repairs'),
    'ripari': ('ree-PAH-ree', 'shelters; covers'),
    'riparo': ('ree-PAH-roh', 'shelter; cover'),
    'ripensamento': ('ree-pen-sah-MEN-toh', 'change of mind'),
    'ripercussioni': ('ree-pehr-koos-SYOH-nee', 'repercussions'),
    'ripetizione': ('ree-peh-tee-TSYOH-neh', 'repetition'),
    'ripetizioni': ('ree-peh-tee-TSYOH-nee', 'repetitions'),
    'ripiano': ('ree-PYAH-noh', 'shelf'),
    'riposo': ('ree-POH-zoh', 'rest'),
    'ripostiglio': ('ree-poh-STEE-lyoh', 'storage closet'),
    'ripresa': ('ree-PREH-zah', 'resumption; filming'),
    'riprese': ('ree-PREH-seh', 'shots; takes'),
    'ripulita': ('ree-poo-LEE-tah', 'cleaned up'),
    'risata': ('ree-ZAH-tah', 'laugh'),
    'risate': ('ree-ZAH-teh', 'laughs'),
    'riscaldamento': ('ree-scal-dah-MEN-toh', 'heating; warm-up'),
    'riscaldi': ('ree-SKAL-dee', 'heat it up'),
    'rischi': ('REE-skee', 'risks'),
    'rischio': ('REE-skyoh', 'risk'),
    'rise': ('REE-zeh', 'laughs'),
    'risentimento': ('ree-sen-tee-MEN-toh', 'resentment'),
    'riserva': ('ree-ZER-vah', 'reserve; reservation'),
    'riserve': ('ree-ZER-veh', 'reserves'),
    'risicoltura': ('ree-zee-kohl-TOOR-rah', 'rice cultivation'),
    'risoluzione': ('ree-soh-loo-TSYOH-neh', 'resolution'),
    'risonanza': ('ree-soh-NAHN-tsah', 'resonance'),
    'risorsa': ('ree-SOHR-sah', 'resource'),
    'risorse': ('ree-SOHR-seh', 'resources'),
    'risotto': ('ree-ZOHT-toh', 'risotto'),
    'risparmi': ('ree-SPAR-mee', 'savings'),
    'risparmio': ('ree-SPAR-myoh', 'savings; thrift'),
    'rispetto': ('ree-SPET-toh', 'respect'),
    'rissa': ('REE-sah', 'brawl'),
    'risse': ('REE-seh', 'brawls'),
    'ristorazione': ('ree-stoh-rah-TSYOH-neh', 'restaurant service; catering'),
    'ristrutturazione': ('ree-struht-too-rah-TSYOH-neh', 'renovation; restructuring'),
    'risveglio': ('reez-VEH-lyoh', 'awakening'),
    'ritardata': ('ree-tar-DAH-tah', 'woman with an intellectual disability (feminine)'),
    'ritardato': ('ree-tar-DAH-toh', 'man with an intellectual disability (masculine)'),
    'ritardo': ('ree-TAR-doh', 'delay'),
    'ritegno': ('ree-TEH-nyoh', 'restraint; inhibition'),
    'riti': ('REE-tee', 'rites'),
    'ritmo': ('REET-moh', 'rhythm'),
    'rito': ('REE-toh', 'ritual; rite'),
    'ritocco': ('ree-TOHK-koh', 'retouching; touch-up'),
    'ritratti': ('ree-TRAT-tee', 'portraits'),
    'ritratto': ('ree-TRAT-toh', 'portrait'),
    'riva': ('REE-vah', 'shore; bank'),
    'rivale': ('ree-VAH-leh', 'rival'),
    'rivali': ('ree-VAH-lee', 'rivals'),
    'rive': ('REE-veh', 'shores; banks'),
    'rivelazione': ('ree-veh-lah-TSYOH-neh', 'revelation'),
    'rivenditore': ('ree-ven-dee-TOH-reh', 'retailer; dealer'),
    'riviera': ('ree-VYEH-rah', 'riviera; coast'),
    'rivincita': ('ree-VEEN-chee-tah', 'rematch; revenge'),
    'rivisitazione': ('ree-vee-zee-tah-TSYOH-neh', 'reinterpretation; revisit'),
    'rivista': ('ree-VEES-tah', 'magazine'),
    'riviste': ('ree-VEES-teh', 'magazines'),
    'rivolta': ('ree-VOHL-tah', 'revolt; uprising'),
    'rivoluzione': ('ree-voh-loo-TSYOH-neh', 'revolution'),
    'roba': ('ROH-bah', 'stuff; things'),
    'robot': ('ROH-boht', 'robot'),
    'rocce': ('ROH-cheh', 'rocks'),
    'roccia': ('ROH-chyah', 'rock; cliff'),
    'rock': ('ROK', 'rock music'),
    'rocker': ('ROK-ker', 'rocker'),
    'roditore': ('roh-dee-TOH-reh', 'rodent'),
    'roditori': ('roh-dee-TOH-ree', 'rodents'),
    'romana': ('roh-MAH-nah', 'Roman (feminine)'),
    'romani': ('roh-MAH-nee', 'Romans'),
    'romanizzazione': ('roh-mah-nee-dzah-TSYOH-neh', 'Romanization'),
    'romantici': ('roh-MAHN-tee-chee', 'romantics (masculine)'),
    'romanticismo': ('roh-mahn-tee-CHEEZ-moh', 'romanticism'),
    'romanziere': ('roh-mahn-TSYEH-reh', 'novelist'),
    'rombo': ('ROM-boh', 'rumble; roar'),
    'rompiscatole': ('rohmp-pee-SKAH-toh-leh', 'nuisance'),
    'romulani': ('roh-moo-LAH-nee', 'Romulans'),
    'rondine': ('RON-dee-neh', 'swallow (bird)'),
    'rondini': ('RON-dee-nee', 'swallows'),
    'ronza': ('RON-dzah', 'buzz'),
    'rosa': ('ROH-zah', 'rose'),
    'rosato': ('roh-ZAH-toh', 'rosé wine'),
    'rose': ('ROH-zeh', 'roses'),
    'rospi': ('ROHS-pee', 'toads'),
    'rospo': ('ROHS-poh', 'toad'),
    'rosse': ('ROH-seh', 'red ones (feminine)'),
    'rossetto': ('roh-SET-toh', 'lipstick'),
    'rosso': ('ROHS-soh', 'red (color)'),
    'rotazione': ('roh-tah-TSYOH-neh', 'rotation'),
    'rotella': ('roh-TEL-lah', 'small wheel'),
    'rotta': ('ROHT-tah', 'route; course'),
    'rottame': ('roh-TAH-meh', 'scrap; wreckage'),
    'rottweiler': ('ROHT-vy-luhr', 'Rottweiler'),
    'roulant': ('roo-LAHN', 'moving walkway; treadmill'),
    'roulette': ('roo-LEHT', 'roulette'),
    'roulotte': ('roo-LOHT', 'caravan; trailer'),
    'round': ('ROWND', 'round (bout)'),
    'routine': ('roo-TEEN', 'routine'),
    'rovesci': ('roh-VEH-shee', 'downpours; reversals'),
    'rovescia': ('roh-VEH-shah', 'upside-down side'),
    'rovescio': ('roh-VEH-syoh', 'reverse side; backhand'),
    'rovina': ('roh-VEE-nah', 'ruin; downfall'),
    'rovine': ('roh-VEE-neh', 'ruins'),
    'royalty': ('ROY-al-tee', 'royalties'),
    'rozzezza': ('roh-ZEHT-tsah', 'roughness'),
    'rubinetto': ('roo-bee-NEHT-toh', 'faucet'),
    'rubli': ('ROOB-lee', 'rubles'),
    'rubrica': ('roo-BREE-kah', 'address book; column'),
    'ruga': ('ROO-gah', 'wrinkle'),
    'rugby': ('RUG-bee', 'rugby'),
    'ruggine': ('ROO-jee-neh', 'rust'),
    'ruggito': ('roo-JEE-toh', 'roar'),
    'rughe': ('ROO-geh', 'wrinkles'),
    'rugiada': ('roo-JAH-dah', 'dew'),
    'rullino': ('roo-LEE-noh', 'film roll'),
    'rum': ('ROOM', 'rum'),
    'rumeni': ('roo-MAY-nee', 'Romanians (masculine)'),
    'rumeno': ('roo-MAY-noh', 'Romanian (masculine)'),
    'ruolo': ('ROO-oh-loh', 'role'),
    'ruota': ('ROO-oh-tah', 'wheel'),
    'ruote': ('ROO-oh-teh', 'wheels'),
    'rupe': ('ROO-peh', 'cliff; crag'),
    'ruppe': ('ROOP-peh', 'broke'),
    'ruscello': ('roo-SHEL-loh', 'stream; brook'),
    'russi': ('ROOS-see', 'Russians (masculine)'),
    'russo': ('ROOS-soh', 'Russian (masculine)'),
    'rutto': ('ROOT-toh', 'burp'),
}

root = Path('vocabulary/dataframes/NOUN')

missing = []
for path in sorted(root.glob('r*.tsv')):
    if path.name == 'r_words_template.tsv':
        continue
    rows = list(csv.DictReader(path.open(encoding='utf-8'), delimiter='\t'))
    if not rows:
        continue
    if 'translation_en' not in rows[0] or 'pronunciation' not in rows[0]:
        raise SystemExit(f"Missing expected columns in {path}")
    needs = any(not row['translation_en'].strip() or not row['pronunciation'].strip() for row in rows)
    if not needs:
        continue
    missing.append(path)

for path in missing:
    rows = list(csv.DictReader(path.open(encoding='utf-8'), delimiter='\t'))
    for row in rows:
        text = row['text']
        if text not in entries:
            raise SystemExit(f"Missing entry for {text} in {path.name}")
        pron, trans = entries[text]
        row['pronunciation'] = pron
        row['translation_en'] = trans
    with path.open('w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys(), delimiter='\t', lineterminator='\n')
        writer.writeheader()
        writer.writerows(rows)

print(f"Updated {len(missing)} files with {len(entries)} entries.")
