from pathlib import Path
import csv

ENTRIES = [
    ('vocabulary/dataframes/VERB/taccheggiare.tsv', 'taccheggiare', 'tahk-kehj-JAH-reh', 'to shoplift'),
    ('vocabulary/dataframes/VERB/tacere.tsv', 'tacere', 'tah-CHEH-reh', 'to keep quiet'),
    ('vocabulary/dataframes/VERB/tacere.tsv', 'taci', 'TAH-chee', '(you) keep quiet'),
    ('vocabulary/dataframes/VERB/tacere.tsv', 'tace', 'TAH-cheh', 'he/she/it keeps quiet'),
    ('vocabulary/dataframes/VERB/tacere.tsv', 'taccia', 'TAHT-chah', 'you (formal) keep quiet'),
    ('vocabulary/dataframes/VERB/tacere.tsv', 'tacete', 'tah-CHEH-teh', 'you (plural) keep quiet'),
    ('vocabulary/dataframes/VERB/tacere.tsv', 'tacciono', 'TAHT-choh-noh', 'they keep quiet'),
    ('vocabulary/dataframes/VERB/taglialare.tsv', 'tagliala', 'tahl-YAH-lah', '(you) cut it'),
    ('vocabulary/dataframes/VERB/tagliateve.tsv', 'tagliatevi', 'tahl-YAH-teh-vee', 'you (plural) cut yourselves'),
    ('vocabulary/dataframes/VERB/taglio.tsv', 'taglio', 'TAHL-yoh', 'I cut'),
    ('vocabulary/dataframes/VERB/taglio.tsv', 'tagli', 'TAHL-yee', 'you cut'),
    ('vocabulary/dataframes/VERB/tamburallare.tsv', 'tamburellava', 'tahm-boo-rel-LAH-vah', 'he/she/it drummed'),
    ('vocabulary/dataframes/VERB/tamburellare.tsv', 'tamburellare', 'tahm-boo-rel-LAH-reh', 'to drum'),
    ('vocabulary/dataframes/VERB/tanere.tsv', 'tacete', 'tah-CHEH-teh', 'you (plural) keep quiet'),
    ('vocabulary/dataframes/VERB/tappare.tsv', 'tappati', 'TAHP-pah-tee', 'plugged (masculine) (plural)'),
    ('vocabulary/dataframes/VERB/tappare.tsv', 'tappata', 'tahp-PAH-tah', 'plugged (feminine)'),
    ('vocabulary/dataframes/VERB/tappatevere.tsv', 'tappatevi', 'tahp-PAH-teh-vee', 'you (plural) shut yourselves up'),
    ('vocabulary/dataframes/VERB/tappo.tsv', 'tappi', 'TAHP-pee', 'you plug'),
    ('vocabulary/dataframes/VERB/tardare.tsv', 'tardato', 'tar-DAH-toh', 'been late (masculine)'),
    ('vocabulary/dataframes/VERB/tastare.tsv', 'tastare', 'tah-STAH-reh', 'to touch'),
    ('vocabulary/dataframes/VERB/tastare.tsv', 'tastate', 'tah-STAH-teh', 'you (plural) touch'),
    ('vocabulary/dataframes/VERB/tasto.tsv', 'tasti', 'TAH-stee', 'you touch'),
    ('vocabulary/dataframes/VERB/tatuare.tsv', 'tatuate', 'tah-too-AH-teh', 'tattooed (feminine) (plural)'),
    ('vocabulary/dataframes/VERB/tatuato.tsv', 'tatuati', 'tah-too-AH-tee', 'tattooed (masculine) (plural)'),
    ('vocabulary/dataframes/VERB/telefonare.tsv', 'telefonato', 'teh-leh-foh-NAH-toh', 'phoned (masculine)'),
    ('vocabulary/dataframes/VERB/telefonare.tsv', 'telefonare', 'teh-leh-foh-NAH-reh', 'to phone'),
    ('vocabulary/dataframes/VERB/telefonare.tsv', 'telefonerò', 'teh-leh-foh-neh-ROH', 'I will phone'),
    ('vocabulary/dataframes/VERB/telefonare.tsv', 'telefona', 'teh-leh-FOH-nah', 'he/she/it phones'),
    ('vocabulary/dataframes/VERB/telefonare.tsv', 'telefonò', 'teh-leh-foh-NOH', 'he/she/it phoned'),
    ('vocabulary/dataframes/VERB/telefonare.tsv', 'telefonarmi', 'teh-leh-foh-NAR-mee', 'to phone me'),
    ('vocabulary/dataframes/VERB/telefonare.tsv', 'telefonategli', 'teh-leh-foh-NAH-teh-lyee', 'you (plural) phone him'),
    ('vocabulary/dataframes/VERB/telefonare.tsv', 'telefonami', 'teh-leh-FOH-nah-mee', '(you) phone me'),
    ('vocabulary/dataframes/VERB/telefonare.tsv', 'telefono', 'teh-LEH-foh-noh', 'I phone'),
    ('vocabulary/dataframes/VERB/telefonare.tsv', 'telefonargli', 'teh-leh-foh-NAR-lyee', 'to phone him'),
    ('vocabulary/dataframes/VERB/telefonare.tsv', 'telefonai', 'teh-leh-foh-NAI', 'I phoned'),
    ('vocabulary/dataframes/VERB/temperare.tsv', 'temperato', 'tem-peh-RAH-toh', 'tempered (masculine)'),
    ('vocabulary/dataframes/VERB/tempestare.tsv', 'tempestava', 'tem-peh-STAH-vah', 'he/she/it pestered'),
    ('vocabulary/dataframes/VERB/tendere.tsv', 'tende', 'TEN-deh', 'he/she/it tends'),
    ('vocabulary/dataframes/VERB/tendere.tsv', 'tendiamo', 'ten-DYAH-moh', 'we tend'),
    ('vocabulary/dataframes/VERB/tendere.tsv', 'tendono', 'TEN-doh-noh', 'they tend'),
    ('vocabulary/dataframes/VERB/tendere.tsv', 'tendo', 'TEN-doh', 'I tend'),
    ('vocabulary/dataframes/VERB/tendere.tsv', 'tendeva', 'ten-DEH-vah', 'he/she/it tended'),
    ('vocabulary/dataframes/VERB/tendere.tsv', 'tendergli', 'ten-DER-lyee', 'to set a trap for him'),
    ('vocabulary/dataframes/VERB/tendere.tsv', 'tendi', 'TEN-dee', 'you tend'),
    ('vocabulary/dataframes/VERB/tendere.tsv', 'tendete', 'ten-DEH-teh', 'you (plural) tend'),
    ('vocabulary/dataframes/VERB/tendere.tsv', 'tese', 'TEH-zeh', 'tense (feminine) (plural)'),
    ('vocabulary/dataframes/VERB/tenermelare.tsv', 'tenermela', 'teh-NEHR-meh-lah', 'to hold it for me'),
    ('vocabulary/dataframes/VERB/tenermelo.tsv', 'tenermelo', 'teh-NEHR-meh-loh', 'to hold it for me'),
    ('vocabulary/dataframes/VERB/teniamoci.tsv', 'teniamoci', 'teh-NYAH-moh-chee', "let's keep in touch"),
    ('vocabulary/dataframes/VERB/tentare.tsv', 'tentato', 'ten-TAH-toh', 'attempted (masculine)'),
    ('vocabulary/dataframes/VERB/tentare.tsv', 'tentare', 'ten-TAH-reh', 'to try'),
    ('vocabulary/dataframes/VERB/tentare.tsv', 'tentò', 'ten-TOH', 'he/she/it tried'),
    ('vocabulary/dataframes/VERB/tentare.tsv', 'tentata', 'ten-TAH-tah', 'tempted (feminine)'),
    ('vocabulary/dataframes/VERB/tentare.tsv', 'tentando', 'ten-TAHN-doh', 'trying'),
    ('vocabulary/dataframes/VERB/tentare.tsv', 'tenterò', 'ten-teh-ROH', 'I will try'),
    ('vocabulary/dataframes/VERB/tentare.tsv', 'tenta', 'TEN-tah', 'he/she/it tries'),
    ('vocabulary/dataframes/VERB/tentare.tsv', 'tentarmi', 'ten-TAR-mee', 'to tempt me'),
    ('vocabulary/dataframes/VERB/tergivere.tsv', 'tergiversi', 'tehr-jee-VER-see', 'you beat around the bush'),
    ('vocabulary/dataframes/VERB/tergiversare.tsv', 'tergiversare', 'tehr-jee-ver-SAH-reh', 'to beat around the bush'),
    ('vocabulary/dataframes/VERB/tergiversare.tsv', 'tergiversando', 'tehr-jee-ver-SAHN-doh', 'beating around the bush'),
    ('vocabulary/dataframes/VERB/tergiversare.tsv', 'tergiversate', 'tehr-jee-ver-SAH-teh', 'you (plural) beat around the bush'),
    ('vocabulary/dataframes/VERB/terminare.tsv', 'terminato', 'tehr-mee-NAH-toh', 'finished (masculine)'),
    ('vocabulary/dataframes/VERB/terminare.tsv', 'terminata', 'tehr-mee-NAH-tah', 'finished (feminine)'),
    ('vocabulary/dataframes/VERB/terminare.tsv', 'termineremo', 'tehr-mee-neh-REH-moh', 'we will finish'),
    ('vocabulary/dataframes/VERB/terminare.tsv', 'termina', 'TEHR-mee-nah', 'he/she/it finishes'),
    ('vocabulary/dataframes/VERB/terminare.tsv', 'terminò', 'tehr-mee-NOH', 'he/she/it finished'),
    ('vocabulary/dataframes/VERB/terminare.tsv', 'terminare', 'tehr-mee-NAH-reh', 'to finish'),
    ('vocabulary/dataframes/VERB/terminare.tsv', 'terminano', 'TEHR-mee-nah-noh', 'they finish'),
    ('vocabulary/dataframes/VERB/terminare.tsv', 'terminerà', 'tehr-mee-neh-RAH', 'he/she/it will finish'),
    ('vocabulary/dataframes/VERB/terrificare.tsv', 'terrificato', 'tehr-ree-fee-KAH-toh', 'terrified (masculine)'),
    ('vocabulary/dataframes/VERB/terrificare.tsv', 'terrificata', 'tehr-ree-fee-KAH-tah', 'terrified (feminine)'),
    ('vocabulary/dataframes/VERB/terrorizzare.tsv', 'terrorizzato', 'tehr-roh-reet-tsah-TOH', 'terrified (masculine)'),
    ('vocabulary/dataframes/VERB/terrorizzare.tsv', 'terrorizzata', 'tehr-roh-reet-tsah-TAH', 'terrified (feminine)'),
    ('vocabulary/dataframes/VERB/terrorizzare.tsv', 'terrorizzava', 'tehr-roh-reet-tsah-VAH', 'he/she/it terrified'),
    ('vocabulary/dataframes/VERB/terrorizzare.tsv', 'terrorizza', 'tehr-roh-REET-tsah', 'he/she/it terrifies'),
    ('vocabulary/dataframes/VERB/terrorizzare.tsv', 'terrorizzate', 'tehr-roh-reet-tsah-TEH', 'terrified (feminine) (plural)'),
    ('vocabulary/dataframes/VERB/terrorizzato.tsv', 'terrorizzati', 'tehr-roh-reet-tsah-TEE', 'terrified (masculine) (plural)'),
    ('vocabulary/dataframes/VERB/teso.tsv', 'teso', 'TEH-zoh', 'stretched (masculine)'),
    ('vocabulary/dataframes/VERB/tessere.tsv', 'tessendo', 'teh-SEHN-doh', 'weaving'),
    ('vocabulary/dataframes/VERB/tessere.tsv', 'tessono', 'TEH-soh-noh', 'they weave'),
    ('vocabulary/dataframes/VERB/testare.tsv', 'testare', 'teh-STAH-reh', 'to test'),
    ('vocabulary/dataframes/VERB/testare.tsv', 'testando', 'teh-STAHN-doh', 'testing'),
    ('vocabulary/dataframes/VERB/testimoniare.tsv', 'testimoniò', 'teh-stee-moh-NYOH', 'he/she/it testified'),
    ('vocabulary/dataframes/VERB/testimoniare.tsv', 'testimoniato', 'teh-stee-moh-nyah-TOH', 'testified (masculine)'),
    ('vocabulary/dataframes/VERB/testimoniare.tsv', 'testimonierò', 'teh-stee-moh-nyeh-ROH', 'I will testify'),
    ('vocabulary/dataframes/VERB/testimoniare.tsv', 'testimonierei', 'teh-stee-moh-nyeh-RAY', 'I would testify'),
    ('vocabulary/dataframes/VERB/testimoniare.tsv', 'testimoniare', 'teh-stee-moh-NYAH-reh', 'to testify'),
    ('vocabulary/dataframes/VERB/tienile.tsv', 'tienilo', 'TYEH-nee-loh', '(you) keep it'),
    ('vocabulary/dataframes/VERB/tienile.tsv', 'tienila', 'TYEH-nee-lah', '(you) keep it (feminine)'),
    ('vocabulary/dataframes/VERB/tienire.tsv', 'tieniti', 'TYEH-nee-tee', '(you) keep yourself'),
    ('vocabulary/dataframes/VERB/tienire.tsv', 'tienilo', 'TYEH-nee-loh', '(you) keep it'),
    ('vocabulary/dataframes/VERB/tienitelare.tsv', 'tienitela', 'TYEH-nee-teh-lah', '(you) keep it for yourself'),
    ('vocabulary/dataframes/VERB/tienitele.tsv', 'tienitelo', 'TYEH-nee-teh-loh', '(you) keep it for yourself'),
    ('vocabulary/dataframes/VERB/tifare.tsv', 'tifando', 'tee-FAHN-doh', 'rooting for'),
    ('vocabulary/dataframes/VERB/timbro.tsv', 'timbro', 'TEEM-broh', 'I stamp'),
    ('vocabulary/dataframes/VERB/tingere.tsv', 'tinto', 'TEEN-toh', 'dyed (masculine)'),
    ('vocabulary/dataframes/VERB/tingere.tsv', 'tingendo', 'teen-JEHN-doh', 'dyeing'),
    ('vocabulary/dataframes/VERB/tingere.tsv', 'tingere', 'TEEN-jeh-reh', 'to dye'),
    ('vocabulary/dataframes/VERB/tinta.tsv', 'tinta', 'TEEN-tah', 'dyed (feminine)'),
    ('vocabulary/dataframes/VERB/tinta.tsv', 'tinte', 'TEEN-teh', 'dyed (feminine) (plural)'),
    ('vocabulary/dataframes/VERB/tinteggiare.tsv', 'tinteggiando', 'teen-tehj-JAHN-doh', 'painting'),
    ('vocabulary/dataframes/VERB/tinto.tsv', 'tinti', 'TEEN-tee', 'dyed (masculine) (plural)'),
    ('vocabulary/dataframes/VERB/tirato.tsv', 'tirate', 'tee-RAH-teh', 'pulled (feminine) (plural)'),
    ('vocabulary/dataframes/VERB/tiro.tsv', 'tiri', 'TEE-ree', 'you pull'),
    ('vocabulary/dataframes/VERB/titolare.tsv', 'titola', 'TEE-toh-lah', 'he/she/it headlines'),
    ('vocabulary/dataframes/VERB/toccandolare.tsv', 'toccandolo', 'tohk-KAHN-doh-loh', 'touching him'),
    ('vocabulary/dataframes/VERB/toccarmare.tsv', 'toccarmi', 'tohk-KAR-mee', 'to touch me'),
    ('vocabulary/dataframes/VERB/toccatemare.tsv', 'toccatemi', 'tohk-KAH-teh-mee', 'you (plural) touch me'),
    ('vocabulary/dataframes/VERB/toglierare.tsv', 'toglierò', 'toh-lyeh-ROH', 'I will remove'),
    ('vocabulary/dataframes/VERB/toglimare.tsv', 'toglimi', 'TOHL-yee-mee', 'you take it off me'),
    ('vocabulary/dataframes/VERB/tolgere.tsv', 'tolgano', 'TOHL-gah-noh', 'that they take away'),
    ('vocabulary/dataframes/VERB/tollare.tsv', 'tollero', 'TOHL-leh-roh', 'I tolerate'),
    ('vocabulary/dataframes/VERB/tollerare.tsv', 'tollererò', 'tohl-leh-reh-ROH', 'I will tolerate'),
    ('vocabulary/dataframes/VERB/tollerare.tsv', 'tollerare', 'tohl-leh-RAH-reh', 'to tolerate'),
    ('vocabulary/dataframes/VERB/tollerare.tsv', 'tollerata', 'tohl-leh-RAH-tah', 'tolerated (feminine)'),
    ('vocabulary/dataframes/VERB/tonare.tsv', 'tonato', 'toh-NAH-toh', 'returned (masculine)'),
    ('vocabulary/dataframes/VERB/tormentare.tsv', 'tormentarmi', 'tohr-men-TAR-mee', 'to torment me'),
    ('vocabulary/dataframes/VERB/tormentare.tsv', 'tormenta', 'tohr-MEN-tah', 'he/she/it torments'),
    ('vocabulary/dataframes/VERB/tormentare.tsv', 'tormentato', 'tohr-men-TAH-toh', 'tormented (masculine)'),
    ('vocabulary/dataframes/VERB/tormentare.tsv', 'tormentarti', 'tohr-men-TAR-tee', 'to torment you'),
    ('vocabulary/dataframes/VERB/tormentare.tsv', 'tormentarla', 'tohr-men-TAR-lah', 'to torment her'),
    ('vocabulary/dataframes/VERB/tormentare.tsv', 'tormentarvi', 'tohr-men-TAR-vee', 'to torment you (plural)'),
    ('vocabulary/dataframes/VERB/tormentare.tsv', 'tormentando', 'tohr-men-TAHN-doh', 'tormenting'),
    ('vocabulary/dataframes/VERB/tormentato.tsv', 'tormentata', 'tohr-men-TAH-tah', 'tormented (feminine)'),
    ('vocabulary/dataframes/VERB/torno.tsv', 'torno', 'TOR-noh', 'I return'),
    ('vocabulary/dataframes/VERB/torre.tsv', 'torrebbono', 'tohr-REB-boh-noh', 'they would take away'),
    ('vocabulary/dataframes/VERB/torto.tsv', 'torto', 'TOR-toh', 'wrong (masculine)'),
    ('vocabulary/dataframes/VERB/torturare.tsv', 'torturare', 'tohr-too-RAH-reh', 'to torture'),
    ('vocabulary/dataframes/VERB/torturare.tsv', 'torturato', 'tohr-too-RAH-toh', 'tortured (masculine)'),
    ('vocabulary/dataframes/VERB/torturare.tsv', 'torturando', 'tohr-too-RAHN-doh', 'torturing'),
    ('vocabulary/dataframes/VERB/torturare.tsv', 'torturarsi', 'tohr-too-RAHR-see', 'to torture oneself'),
    ('vocabulary/dataframes/VERB/torturare.tsv', 'torturarti', 'tohr-too-RAHR-tee', 'to torture yourself'),
    ('vocabulary/dataframes/VERB/tossere.tsv', 'tossendo', 'tohs-SEN-doh', 'coughing'),
    ('vocabulary/dataframes/VERB/tossire.tsv', 'tossire', 'toh-SEER-eh', 'to cough'),
    ('vocabulary/dataframes/VERB/traboccare.tsv', 'traboccare', 'trah-bohk-KAH-reh', 'to overflow'),
    ('vocabulary/dataframes/VERB/tracciare.tsv', 'traccia', 'TRAH-chah', 'he/she/it draws'),
    ('vocabulary/dataframes/VERB/tracciare.tsv', 'tracci', 'TRAH-chee', 'you draw'),
    ('vocabulary/dataframes/VERB/tracciare.tsv', 'tracciate', 'TRAH-chah-teh', 'drawn (feminine) (plural)'),
    ('vocabulary/dataframes/VERB/tradere.tsv', 'tradendo', 'trah-DEHN-doh', 'cheating'),
    ('vocabulary/dataframes/VERB/tradire.tsv', 'tradito', 'trah-DEE-toh', 'betrayed (masculine)'),
    ('vocabulary/dataframes/VERB/tradire.tsv', 'tradì', 'trah-DEE', 'he/she/it betrayed'),
    ('vocabulary/dataframes/VERB/tradire.tsv', 'tradita', 'trah-DEE-tah', 'betrayed (feminine)'),
    ('vocabulary/dataframes/VERB/tradire.tsv', 'tradirei', 'trah-dee-RAY', 'I would betray'),
    ('vocabulary/dataframes/VERB/tradire.tsv', 'tradire', 'trah-DEER-eh', 'to betray'),
    ('vocabulary/dataframes/VERB/tradire.tsv', 'tradirò', 'trah-dee-ROH', 'I will betray'),
    ('vocabulary/dataframes/VERB/tradire.tsv', 'tradite', 'trah-DEE-teh', 'betrayed (feminine) (plural)'),
    ('vocabulary/dataframes/VERB/tradire.tsv', 'traditi', 'trah-DEE-tee', 'betrayed (masculine) (plural)'),
    ('vocabulary/dataframes/VERB/tradire.tsv', 'tradirebbe', 'trah-dee-REB-beh', 'he/she/it would betray'),
    ('vocabulary/dataframes/VERB/tradire.tsv', 'tradirvi', 'trah-DEER-vee', 'to betray you (plural)'),
    ('vocabulary/dataframes/VERB/tradire.tsv', 'tradiva', 'trah-DEE-vah', 'he/she/it was betraying'),
    ('vocabulary/dataframes/VERB/traducare.tsv', 'traduca', 'trah-DOO-kah', 'you translate'),
    ('vocabulary/dataframes/VERB/traducibile.tsv', 'traducibile', 'trah-doo-CHEE-bee-leh', 'translatable'),
    ('vocabulary/dataframes/VERB/traducilare.tsv', 'traducila', 'trah-DOO-chee-lah', 'you translate it'),
    ('vocabulary/dataframes/VERB/trafficare.tsv', 'trafficando', 'trah-fee-KAHN-doh', 'trafficking'),
    ('vocabulary/dataframes/VERB/trainare.tsv', 'trainare', 'trah-ee-NAH-reh', 'to tow'),
    ('vocabulary/dataframes/VERB/trainare.tsv', 'trainando', 'trah-ee-NAHN-doh', 'towing'),
    ('vocabulary/dataframes/VERB/tramandare.tsv', 'tramandata', 'trah-mahn-DAH-tah', 'handed down (feminine)'),
    ('vocabulary/dataframes/VERB/tramare.tsv', 'tramando', 'trah-MAHN-doh', 'plotting'),
    ('vocabulary/dataframes/VERB/tramontare.tsv', 'tramonta', 'trah-MON-tah', 'he/she/it sets'),
    ('vocabulary/dataframes/VERB/tramontare.tsv', 'tramontare', 'trah-mon-TAH-reh', 'to set'),
    ('vocabulary/dataframes/VERB/tramontare.tsv', 'tramontando', 'trah-mon-TAHN-doh', 'setting'),
    ('vocabulary/dataframes/VERB/tramontare.tsv', 'tramontato', 'trah-mon-TAH-toh', 'set (masculine)'),
    ('vocabulary/dataframes/VERB/tranquililizare.tsv', 'tranquillizzarla', 'trahn-kweel-leed-ZAHR-lah', 'to calm her down'),
    ('vocabulary/dataframes/VERB/tranquillizzare.tsv', 'tranquillizzare', 'trahn-kweel-leed-ZAH-reh', 'to calm down'),
    ('vocabulary/dataframes/VERB/tranquillizzare.tsv', 'tranquillizzò', 'trahn-kweel-leed-ZOH', 'he/she/it calmed down'),
    ('vocabulary/dataframes/VERB/trapelare.tsv', 'trapelare', 'trah-peh-LAH-reh', 'to leak out'),
    ('vocabulary/dataframes/VERB/trarre.tsv', 'trarre', 'TRAR-reh', 'to draw'),
    ('vocabulary/dataframes/VERB/trarre.tsv', 'tratto', 'TRAT-toh', 'drawn (masculine)'),
    ('vocabulary/dataframes/VERB/trarre.tsv', 'traendo', 'trah-EN-doh', 'drawing'),
    ('vocabulary/dataframes/VERB/trarre.tsv', 'trae', 'TRAH-eh', 'he/she/it draws'),
    ('vocabulary/dataframes/VERB/trasandare.tsv', 'trasandato', 'trah-sahn-DAH-toh', 'sloppy (masculine)'),
    ('vocabulary/dataframes/VERB/trascinare.tsv', 'trascinò', 'trah-shee-NOH', 'he/she/it dragged'),
    ('vocabulary/dataframes/VERB/trascinare.tsv', 'trascinato', 'trah-shee-NAH-toh', 'dragged (masculine)'),
    ('vocabulary/dataframes/VERB/trascinare.tsv', 'trascinarlo', 'trah-shee-NAHR-loh', 'to drag him'),
    ('vocabulary/dataframes/VERB/trascinare.tsv', 'trascinata', 'trah-shee-NAH-tah', 'dragged (feminine)'),
    ('vocabulary/dataframes/VERB/trascinare.tsv', 'trascinarvi', 'trah-shee-NAHR-vee', 'to drag you (plural)'),
    ('vocabulary/dataframes/VERB/trascinare.tsv', 'trascinati', 'trah-shee-NAH-tee', 'dragged (masculine) (plural)'),
    ('vocabulary/dataframes/VERB/trascinare.tsv', 'trascinate', 'trah-shee-NAH-teh', 'dragged (feminine) (plural)'),
    ('vocabulary/dataframes/VERB/trascrivere.tsv', 'trascrivere', 'trahs-KREE-veh-reh', 'to transcribe'),
    ('vocabulary/dataframes/VERB/trascurare.tsv', 'trascurare', 'trahs-koo-RAH-reh', 'to neglect'),
    ('vocabulary/dataframes/VERB/trascurare.tsv', 'trascurando', 'trahs-koo-RAHN-doh', 'neglecting'),
    ('vocabulary/dataframes/VERB/trascurare.tsv', 'trascurato', 'trahs-koo-RAH-toh', 'neglected (masculine)'),
    ('vocabulary/dataframes/VERB/trascurare.tsv', 'trascura', 'trahs-KOO-rah', 'he/she/it neglects'),
    ('vocabulary/dataframes/VERB/trasformare.tsv', 'trasforma', 'trahs-FOR-mah', 'he/she/it transforms'),
    ('vocabulary/dataframes/VERB/trasformare.tsv', 'trasformata', 'trahs-for-MAH-tah', 'transformed (feminine)'),
    ('vocabulary/dataframes/VERB/trasformare.tsv', 'trasformato', 'trahs-for-MAH-toh', 'transformed (masculine)'),
    ('vocabulary/dataframes/VERB/trasformare.tsv', 'trasformò', 'trahs-for-MOH', 'he/she/it transformed'),
    ('vocabulary/dataframes/VERB/trasformare.tsv', 'trasformano', 'trahs-FOR-mah-noh', 'they transform'),
    ('vocabulary/dataframes/VERB/trasformare.tsv', 'trasformate', 'trahs-for-MAH-teh', 'transformed (feminine) (plural)'),
    ('vocabulary/dataframes/VERB/trasformare.tsv', 'trasformo', 'trahs-FOR-moh', 'I transform'),
    ('vocabulary/dataframes/VERB/trasformare.tsv', 'trasformare', 'trahs-for-MAH-reh', 'to transform'),
    ('vocabulary/dataframes/VERB/trasformare.tsv', 'trasformarsi', 'trahs-for-MAR-see', 'to transform oneself'),
    ('vocabulary/dataframes/VERB/trasformare.tsv', 'trasformi', 'trahs-FOR-mee', 'that he/she transforms'),
    ('vocabulary/dataframes/VERB/trasformare.tsv', 'trasformerò', 'trahs-for-meh-ROH', 'I will transform'),
    ('vocabulary/dataframes/VERB/trasformare.tsv', 'trasformerà', 'trahs-for-meh-RAH', 'he/she/it will transform'),
    ('vocabulary/dataframes/VERB/trasgredire.tsv', 'trasgredire', 'trahs-greh-DEER-eh', 'to break the rules'),
    ('vocabulary/dataframes/VERB/traslocare.tsv', 'traslocare', 'trahs-loh-KAH-reh', 'to move house'),
    ('vocabulary/dataframes/VERB/traslocare.tsv', 'traslocato', 'trahs-loh-KAH-toh', 'moved (masculine)'),
    ('vocabulary/dataframes/VERB/traslocare.tsv', 'traslocando', 'trahs-loh-KAHN-doh', 'moving house'),
    ('vocabulary/dataframes/VERB/trasloco.tsv', 'trasloco', 'trahs-LOH-koh', 'I move house'),
    ('vocabulary/dataframes/VERB/trasmettere.tsv', 'trasmessi', 'trahs-MES-see', 'broadcast (masculine) (plural)'),
    ('vocabulary/dataframes/VERB/trasmettere.tsv', 'trasmettono', 'trahs-MET-toh-noh', 'they broadcast'),
    ('vocabulary/dataframes/VERB/trasmettere.tsv', 'trasmesso', 'trahs-MES-soh', 'broadcast (masculine)'),
    ('vocabulary/dataframes/VERB/trasmettere.tsv', 'trasmettendo', 'trahs-met-TEN-doh', 'broadcasting'),
    ('vocabulary/dataframes/VERB/trasmettere.tsv', 'trasmette', 'trahs-MET-teh', 'he/she/it transmits'),
    ('vocabulary/dataframes/VERB/trasmettere.tsv', 'trasmetterla', 'trahs-MET-ter-lah', 'to transmit it (feminine)'),
    ('vocabulary/dataframes/VERB/trasmettere.tsv', 'trasmessa', 'trahs-MES-sah', 'broadcast (feminine)'),
    ('vocabulary/dataframes/VERB/traspirare.tsv', 'traspirando', 'trahs-pee-RAHN-doh', 'perspiring'),
    ('vocabulary/dataframes/VERB/trasportare.tsv', 'trasportare', 'trahs-por-TAH-reh', 'to transport'),
    ('vocabulary/dataframes/VERB/trasportare.tsv', 'trasportato', 'trahs-por-TAH-toh', 'transported (masculine)'),
    ('vocabulary/dataframes/VERB/trasportare.tsv', 'trasportava', 'trahs-por-TAH-vah', 'he/she/it was transporting'),
    ('vocabulary/dataframes/VERB/trasportare.tsv', 'trasportando', 'trahs-por-TAHN-doh', 'transporting'),
    ('vocabulary/dataframes/VERB/trasportare.tsv', 'trasporta', 'trahs-POR-tah', 'he/she/it transports'),
    ('vocabulary/dataframes/VERB/trasportare.tsv', 'trasportati', 'trahs-por-TAH-tee', 'transported (masculine) (plural)'),
    ('vocabulary/dataframes/VERB/trasportare.tsv', 'trasportano', 'trahs-POR-tah-noh', 'they transport'),
    ('vocabulary/dataframes/VERB/trasportare.tsv', 'trasportarla', 'trahs-por-TAR-lah', 'to transport it (feminine)'),
    ('vocabulary/dataframes/VERB/trasportare.tsv', 'trasportò', 'trahs-por-TOH', 'he/she/it transported'),
    ('vocabulary/dataframes/VERB/trasudare.tsv', 'trasudano', 'trahs-OO-dah-noh', 'they exude'),
    ('vocabulary/dataframes/VERB/trattatemere.tsv', 'trattatemi', 'trah-TTAH-teh-mee', 'you (plural) treat me'),
    ('vocabulary/dataframes/VERB/tratteggiare.tsv', 'tratteggiata', 'traht-tehj-JAH-tah', 'dashed (feminine)'),
    ('vocabulary/dataframes/VERB/trattenere.tsv', 'trattenere', 'trah-teh-NEH-reh', 'to hold back'),
    ('vocabulary/dataframes/VERB/trattenere.tsv', 'trattenuto', 'trah-teh-NOO-toh', 'held back (masculine)'),
    ('vocabulary/dataframes/VERB/trattenere.tsv', 'trattenete', 'trah-teh-NEH-teh', 'you (plural) hold back'),
    ('vocabulary/dataframes/VERB/trattenere.tsv', 'trattenga', 'trah-TEN-gah', 'you (formal) hold'),
    ('vocabulary/dataframes/VERB/trattenere.tsv', 'trattenne', 'trah-TEN-neh', 'he/she/it held back'),
    ('vocabulary/dataframes/VERB/trattenere.tsv', 'trattenermi', 'trah-teh-NER-mee', 'to hold myself back'),
    ('vocabulary/dataframes/VERB/trattenere.tsv', 'trattieni', 'trah-TYEN-ee', 'you hold'),
    ('vocabulary/dataframes/VERB/trattenere.tsv', 'trattenersi', 'trah-teh-NER-see', 'to hold oneself back'),
    ('vocabulary/dataframes/VERB/tratterrare.tsv', 'tratterrà', 'trah-tehr-RAH', 'he/she/it will hold back'),
    ('vocabulary/dataframes/VERB/trattiare.tsv', 'trattiate', 'trah-TYAH-teh', 'that you (plural) treat'),
    ('vocabulary/dataframes/VERB/traumatizzare.tsv', 'traumatizzato', 'trah-oo-mah-tee-ZAH-toh', 'traumatized (masculine)'),
    ('vocabulary/dataframes/VERB/travessire.tsv', 'travestì', 'trah-ves-TEE', 'he/she/it disguised himself/herself'),
    ('vocabulary/dataframes/VERB/travestito.tsv', 'travestito', 'trah-ves-TEE-toh', 'disguised (masculine)'),
    ('vocabulary/dataframes/VERB/travestito.tsv', 'travestiti', 'trah-ves-TEE-tee', 'disguised (masculine) (plural)'),
    ('vocabulary/dataframes/VERB/travolgere.tsv', 'travolto', 'trah-VOHL-toh', 'run over (masculine)'),
    ('vocabulary/dataframes/VERB/tremare.tsv', 'tremare', 'treh-MAH-reh', 'to tremble'),
    ('vocabulary/dataframes/VERB/tremare.tsv', 'tremando', 'treh-MAHN-doh', 'trembling'),
    ('vocabulary/dataframes/VERB/tremare.tsv', 'tremava', 'treh-MAH-vah', 'he/she/it was trembling'),
    ('vocabulary/dataframes/VERB/tremare.tsv', 'tremavano', 'treh-MAH-vah-noh', 'they were trembling'),
    ('vocabulary/dataframes/VERB/tremare.tsv', 'tremo', 'TREH-moh', 'I tremble'),
    ('vocabulary/dataframes/VERB/trincerare.tsv', 'trincerato', 'treen-cheh-RAH-toh', 'entrenched (masculine)'),
    ('vocabulary/dataframes/VERB/triplicare.tsv', 'triplicata', 'tree-plee-KAH-tah', 'tripled (feminine)'),
    ('vocabulary/dataframes/VERB/triturare.tsv', 'triturati', 'tree-too-RAH-tee', 'shredded (masculine) (plural)'),
    ('vocabulary/dataframes/VERB/trollare.tsv', 'trollare', 'trohl-LAH-reh', 'to troll'),
]

def apply_updates(entries=ENTRIES):
    """Populate pronunciation/translation columns for t-initial verb TSVs."""

    updates = {}
    for path, text, pron, translation in entries:
        updates.setdefault(path, {})[text] = (pron, translation)

    for rel_path, mapping in updates.items():
        path = Path(rel_path)
        with path.open(newline='') as fh:
            reader = csv.DictReader(fh, delimiter='\t')
            rows = list(reader)
            fieldnames = reader.fieldnames
        for row in rows:
            if row['text'] in mapping:
                pron, translation = mapping[row['text']]
                row['pronunciation'] = pron
                row['translation_en'] = translation
        with path.open('w', newline='') as fh:
            writer = csv.DictWriter(
                fh, fieldnames=fieldnames, delimiter='\t', lineterminator='\n'
            )
            writer.writeheader()
            writer.writerows(rows)


if __name__ == '__main__':
    apply_updates()
