from __future__ import annotations

import csv
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from utils.add_pronunciation_column import pronounce_word

DATA_DIR = Path('vocabulary/dataframes/NOUN')

TRANSLATIONS = {
    'cabaret': 'cabaret show',
    'cabarettista': 'cabaret performer',
    'cabina': 'cabin; booth',
    'cabine': 'cabins; booths',
    'cabinato': 'cabin cruiser',
    'cacca': 'poop',
    'caccia': 'hunt; hunting',
    'cacciatore': 'hunter (masculine)',
    'cacciatrice': 'hunter (feminine)',
    'cacciatori': 'hunters (masculine)',
    'cacciavite': 'screwdriver',
    'cacciaviti': 'screwdrivers',
    'cactus': 'cactus',
    'cadavere': 'corpse',
    'cadaveri': 'corpses',
    'cadmio': 'cadmium',
    'caduta': 'fall; drop',
    'caffetteria': 'coffee shop; café',
    'caffèlatte': 'caffè latte; coffee with milk',
    'cafone': 'boor; lout',
    'caghi': 'shits',
    'cagasotto': 'cowards; chickenshits',
    'cagna': 'female dog',
    'cagnolino': 'puppy; little dog',
    'cago': 'I shit',
    'calabroni': 'hornets',
    'calabrone': 'hornet',
    'calamaro': 'squid',
    'calamari': 'squid (plural)',
    'calamita': 'magnet',
    'calamite': 'magnets',
    'calamità': 'calamity; disaster',
    'calar': 'fall; descent',
    'calcagna': 'heels',
    'calciatore': 'soccer player (masculine)',
    'calciatori': 'soccer players (masculine)',
    'calciatrici': 'soccer players (feminine)',
    'calcolatrice': 'calculator (feminine)',
    'calcolatore': 'calculator; computer (masculine)',
    'calcolo': 'calculation; computation',
    'calcoli': 'calculations; computations',
    'caldaia': 'boiler',
    'caldaie': 'boilers',
    'caldo': 'heat',
    'calendario': 'calendar',
    'calice': 'chalice; goblet',
    'califfato': 'caliphate',
    'califfo': 'caliph',
    'call': 'call',
    'calligrafia': 'calligraphy',
    'callo': 'callus',
    'calma': 'calm; tranquility',
    'calmata': 'calming down; chill',
    'calmati': 'calm down (plural)',
    'calo': 'drop; decrease',
    'calore': 'heat; warmth',
    'calorie': 'calories',
    'calorifero': 'radiator; heater',
    'calotte': 'domes; caps',
    'calva': 'bald (feminine)',
    'calza': 'stocking; sock',
    'calze': 'stockings; socks',
    'calzini': 'socks',
    'calzino': 'sock',
    'calzolaio': 'cobbler; shoemaker',
    'calzoni': 'pants; trousers',
    'cambiamento': 'change; shift',
    'cambiamenti': 'changes; shifts',
    'cambio': 'change; exchange',
    'cambi': 'change (you)',
    'camelie': 'camellias',
    'cameriera': 'waitress (feminine)',
    'cameriere': 'waiter (masculine)',
    'camerino': 'dressing room',
    'camicetta': 'blouse',
    'camicia': 'shirt',
    'camicie': 'shirts',
    'camino': 'fireplace; chimney',
    'camion': 'truck',
    'camionista': 'truck driver',
    'cammelli': 'camels',
    'cammello': 'camel',
    'camminata': 'walk; stroll',
    'camminatore': 'walker; hiker',
    'cammini': 'you walk',
    'cammino': 'I walk',
    'camomilla': 'chamomile tea',
    'campana': 'bell',
    'campane': 'bells',
    'campanella': 'handbell; small bell',
    'campanello': 'doorbell',
    'campanile': 'bell tower',
    'campeggiatori': 'campers',
    'campeggio': 'campground; camping trip',
    'camper': 'camper van',
    'campionato': 'championship',
    'campione': 'champion',
    'campioni': 'champions',
    'campus': 'campus',
    'canadese': 'Canadian',
    'canadesi': 'Canadians',
    'canale': 'channel; canal',
    'canali': 'channels; canals',
    'canapa': 'hemp',
    'canarino': 'canary',
    'canarini': 'canaries',
    'cancellazione': 'cancellation; deletion',
    'cancelliere': 'chancellor; registrar',
    'cancello': 'gate',
    'cancelli': 'gates',
    'cancro': 'cancer',
    'candeggina': 'bleach',
    'candela': 'candle',
    'candele': 'candles',
    'candelabro': 'candelabrum',
    'candelina': 'small candle',
    'candeline': 'small candles',
    'candidato': 'candidate (masculine)',
    'candidati': 'candidates (masculine)',
    'candidata': 'candidate (feminine)',
    'candidatura': 'candidacy',
    'canguro': 'kangaroo',
    'canguri': 'kangaroos',
    'canili': 'kennels',
    'canile': 'kennel; dog shelter',
    'canna': 'cane; reed',
    'cannabis': 'cannabis; marijuana',
    'cannella': 'cinnamon',
    'cannibale': 'cannibal',
    'cannoni': 'cannons; artillery pieces',
    'canoa': 'canoe',
    'canone': 'canon; fee',
    'cantare': 'sing (infinitive)',
    'canta': 'sings',
    'canterai': 'will you sing',
    'canterete': 'will you all sing',
    'cantina': 'cellar; wine cellar',
    'canto': 'song; canto',
    'canti': 'songs; cantos',
    'cantonese': 'Cantonese language',
    'cantore': 'cantor; singer',
    'caos': 'chaos',
    'capacità': 'ability; capacity',
    'capanna': 'hut',
    'capezzale': 'bedside',
    'capillari': 'capillaries',
    'capirti': 'to understand you',
    'capitalismo': 'capitalism',
    'capitalista': 'capitalist',
    'capitano': 'captain',
    'capite': 'do you get it',
    'capitolo': 'chapter',
    'capitoli': 'chapters',
    'capocuoco': 'head chef (masculine)',
    'capodanno': 'New Year; New Year\'s Day',
    'capofamiglia': 'head of household',
    'capofficina': 'shop foreman',
    'capofitto': 'headlong dive',
    'capogiro': 'dizziness',
    'capogruppo': 'group leader',
    'capolavoro': 'masterpiece',
    'capolavori': 'masterpieces',
    'capolinea': 'end of the line; terminus',
    'capolista': 'lead candidate (feminine)',
    'capoluogo': 'provincial capital',
    'capopattuglia': 'patrol leader',
    'caposala': 'head nurse',
    'capostazione': 'stationmaster',
    'cappa': 'hood; cloak',
    'cappella': 'chapel',
    'cappellano': 'chaplain',
    'cappellino': 'cap; little hat',
    'cappio': 'noose',
    "cappon'": 'capons (before a vowel)',
    'cappotto': 'coat; overcoat',
    'cappuccino': 'cappuccino',
    'capra': 'goat',
    'capre': 'goats',
    'capricci': 'tantrums; whims',
    'capriola': 'somersault; cartwheel',
    'caprone': 'billy goat',
    'caramelle': 'candies',
    'caramella': 'candy',
    'carattere': 'character; personality',
    'caratteri': 'characters; personalities',
    'caratteristica': 'characteristic; feature',
    'caratteristiche': 'characteristics; features',
    'carbonato': 'carbonate',
    'carbone': 'coal',
    'carbonio': 'carbon',
    'carburante': 'fuel',
    'carcassa': 'carcass',
    'carcerati': 'prisoners',
    'carcere': 'prison',
    'cardamomo': 'cardamom',
    'cardini': 'hinges',
    'carenza': 'shortage; lack',
    'carestia': 'famine',
    'carica': 'charge; post',
    'cariche': 'charges; posts',
    'caricatura': 'caricature',
    'carico': 'load; cargo',
    'carichi': 'loads; cargos',
    'carillon': 'carillon; music box',
    'carità': 'charity',
    'carnagione': 'complexion',
    'carnivori': 'carnivores',
    'carni': 'meats',
    'cari': 'dear ones (masculine)',
    'caro': 'my dear (masculine)',
    'carote': 'carrots',
    'carota': 'carrot',
    'carpe': 'carp (plural)',
    'carpentiere': 'carpenter',
    'carreggiata': 'lane; roadway',
    'carrello': 'cart; trolley',
    'carriera': 'career',
    'carro': 'cart; wagon',
    'carrozza': 'carriage',
    'carrozze': 'carriages',
    'carrozzeria': 'body shop; car body',
    'cartella': 'folder; briefcase',
    'cartelle': 'folders; files',
    'cartellino': 'tag; badge',
    'cartello': 'sign; placard',
    'cartelli': 'signs; placards',
    'cartina': 'map; slip of paper',
    'cartolina': 'postcard',
    'cartoline': 'postcards',
    'cartoni': 'cartons; cardboard boxes',
    'cartone': 'cardboard; carton',
    'casalinga': 'housewife',
    'casalinghe': 'housewives',
    'casanova': 'ladies\' man',
    'cascamorto': 'show-off; poseur',
    'cascate': 'waterfalls',
    'caschetti': 'helmets',
    'casco': 'helmet',
    'caschi': 'helmets',
    'casella': 'box; square',
    'casello': 'toll booth',
    'casetta': 'little house; cottage',
    'casino': 'mess; chaos',
    'casinò': 'casino (gambling hall)',
    'casolare': 'farmhouse',
    'cassa': 'cash register; checkout',
    'cassaforte': 'safe; strongbox',
    'casse': 'boxes; crates',
    'cassetta': 'box; cassette',
    'cassetto': 'drawer',
    'cassetti': 'drawers',
    'casso': 'case',
    'cassonetto': 'dumpster; trash bin',
    'cast': 'cast',
    'casta': 'chaste woman',
    'castano': 'brown; chestnut (color)',
    'castello': 'castle',
    'castelli': 'castles',
    'castigo': 'punishment',
    'casto': 'chaste (masculine)',
    'castori': 'beavers',
    'castoro': 'beaver',
    'catalano': 'Catalan',
    'catalessi': 'catalepsy',
    'catalogo': 'catalog',
    'catamarano': 'catamaran',
    'catastrofe': 'catastrophe',
    'categoria': 'category',
    'categorie': 'categories',
    'catena': 'chain',
    'catene': 'chains',
    'catinelle': 'basins; buckets',
    'cattedrale': 'cathedral',
    'cattiveria': 'malice; wickedness',
    'cattivo': 'bad; wicked (masculine)',
    'cattivi': 'bad ones (masculine)',
    'cattiva': 'bad; wicked (feminine)',
    'cattolici': 'Catholics',
    'catture': 'captures',
    'catturi': 'you catch',
    'cautela': 'caution',
    'cauzione': 'bail; bond',
    'caval': 'horse (archaic)',
    'cavalcatura': 'mount; riding horse',
    'cavalier': 'knights',
    'cavalieri': 'knights',
    'cavaliere': 'knight; gentleman',
    'cavalla': 'mare',
    'cavatappi': 'corkscrews',
    'cavi': 'cables',
    'caverna': 'cave',
    'cavie': 'guinea pigs',
    'caviale': 'caviar',
    'caviglia': 'ankle',
    'caviglie': 'ankles',
    'cavo': 'cable; wire',
    'cavolo': 'cabbage',
    'cavoli': 'cabbages',
    'cazzate': 'bullshit; nonsense',
    'cazzo': 'dick',
    'cazzi': 'dicks',
    'cazzoni': 'jerks; dicks',
    'cd.': 'CD',
    'cd': 'CD',
    'ceco': 'Czech (masculine)',
    'ceffone': 'slap; smack',
    'celebrazione': 'celebration',
    'celebrazioni': 'celebrations',
    'celebrità': 'celebrity; fame',
    'cella': 'cell',
    'celle': 'cells',
    'cellule': 'cells',
    'cellulare': 'cell phone',
    'cellulari': 'cell phones',
    'celtico': 'Celtic (masculine)',
    'celti': 'Celts',
    'cemento': 'cement',
    'cenano': 'they have dinner',
    'cenavo': 'I was having dinner',
    'cencio': 'rag',
    'ceni': 'have dinner (you)',
    'cenere': 'ash',
    'ceneri': 'ashes',
    'cenerete': 'will you have dinner',
    'cenerà': 'she will have dinner',
    'cenno': 'gesture; sign',
    'ceno': 'I have dinner',
    'censimento': 'census',
    'censura': 'censorship',
    'centauro': 'centaur',
    'center': 'center',
    'centesimi': 'cents',
    'centesimo': 'cent',
    'centigradi': 'degrees Celsius',
    'centimetri': 'centimeters',
    'cm.': 'centimeter',
    'centimetro': 'centimeter',
    'centinaia': 'hundreds',
    'centinaio': 'hundred',
    'centipede': 'centipede',
    'centododici': 'one hundred and twelve',
    'centrale': 'power plant',
    'centrali': 'power plants',
    'centralizzazione': 'centralization',
    'centrifuga': 'centrifuge',
    'centrista': 'centrist',
    'centro': 'center',
    'centri': 'centers',
    'cenò': 'he or she had dinner',
    'ceppo': 'log; stump',
    'cera': 'wax',
    'ceramica': 'ceramics',
    'ceramiche': 'ceramics (plural)',
    'cerca': 'look for (you)',
    'cerchi': 'you look for',
    'cercatrice': 'seeker (feminine)',
    'cerchia': 'circle; clique',
    'cerchio': 'circle',
    'cereali': 'cereals; grains',
    'cerimonia': 'ceremony',
    'cerniera': 'zipper',
    'cerotto': 'bandage; plaster',
    'certezza': 'certainty',
    'certificati': 'certificates',
    'certificato': 'certificate',
    'cervello': 'brain',
    'cervelli': 'brains',
    'cervice': 'cervix',
    'cervo': 'deer',
    'cervi': 'deer (plural)',
    'cespuglio': 'bush; shrub',
    'cespugli': 'bushes; shrubs',
    'cessazione': 'cessation; termination',
    'cesso': 'toilet; john',
    'cesta': 'basket',
    'cestista': 'basketball player',
    'cesto': 'basket',
    'cestino': 'small basket; wastebasket',
    'ceto': 'social class',
    'ceti': 'social classes',
    'cetriolo': 'cucumber',
    'cetrioli': 'cucumbers',
    'cezyas': 'Tsez language',
    'chai': 'chai tea',
    'chairman': 'chairman',
    'chakra': 'chakra',
    'champagne': 'champagne',
    'champignon': 'champignon mushroom',
    'chat.': 'chat',
    'check': 'check',
    'cheerleader': 'cheerleader',
    'cheese': 'cheese',
    'cheeseburger': 'cheeseburger',
    'chiacchere': 'chatter; gossip',
    'chiacchiere': 'chatter; gossip',
    'chiacchierata': 'chat; talk',
    'chiacchierate': 'chats; talks',
    'chiacchieri': 'you chatter too much',
    'chiacchierona': 'chatterbox (feminine)',
    'chiacchierone': 'chatterbox (masculine)',
    'chiamata': 'phone call',
    'chiamate': 'phone calls',
    'chiarezza': 'clarity',
    'chiaro': 'clear (masculine)',
    'chiavetta': 'USB key; flash drive',
    'chiazza': 'stain; blotch',
    'chicca': 'treat; little gem',
    'chicchi': 'grains; kernels',
    'chierichetti': 'altar boys',
    'chiese': 'churches',
    'chihuahua': 'Chihuahua',
    'chilli': 'chili',
    'chili': 'chili (plural)',
    'chilo': 'kilogram',
    'kg.': 'kilogram',
    'chilogrammi': 'kilograms',
    'chilogrammo': 'kilogram',
    'kg': 'kilogram',
    'chilometri': 'kilometers',
    'km': 'kilometer',
    'chilometro': 'kilometer',
    'chimica': 'chemistry',
    'chioccia': 'broody hen',
    'chiocciola': 'snail; at sign',
    'chiocciole': 'snails',
    'chiodo': 'nail',
    'chiodi': 'nails',
    'microchip': 'microchip',
    'chips': 'chips; crisps',
    'chirurgia': 'surgery',
    'chirurgo': 'surgeon',
    'chitarrista': 'guitarist',
    'chiuso': 'closed (masculine)',
    'chiuse': 'she closed',
    'chiusura': 'closure',
    'chop': 'chop',
}


def load_rows(path: Path):
    with path.open('r', encoding='utf-8', newline='') as handle:
        reader = csv.DictReader(handle, delimiter='\t')
        rows = list(reader)
        fieldnames = reader.fieldnames or []
    return fieldnames, rows


def save_rows(path: Path, fieldnames, rows):
    with path.open('w', encoding='utf-8', newline='') as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter='\t', lineterminator='\n')
        writer.writeheader()
        writer.writerows(rows)


def main():
    targets = []
    for path in sorted(DATA_DIR.glob('c*.tsv')):
        stem = path.name.lower()
        if not ('ca' <= stem[:2] <= 'ch'):
            continue
        fieldnames, rows = load_rows(path)
        updated = False
        for row in rows:
            text = row.get('text', '')
            transl = row.get('translation_en', '').strip()
            pron = row.get('pronunciation', '').strip()
            if transl and pron:
                continue
            if text not in TRANSLATIONS:
                raise KeyError(f'Missing translation for {text!r} in {path.name}')
            row['translation_en'] = TRANSLATIONS[text]
            row['pronunciation'] = pronounce_word(text)
            updated = True
        if updated:
            save_rows(path, fieldnames, rows)
            targets.append(path.name)
    print(f'Updated {len(targets)} files')


if __name__ == '__main__':
    main()
