import csv
import os

BASE_DIR = os.path.join('vocabulary', 'dataframes', 'NOUN')

DATA = [
    ('oasi', 'OH-AH-see', 'oasis'),
    ('obbedienza', 'ohb-beh-DYEN-tsah', 'obedience'),
    ('obbiettivo', 'ohb-byeht-TEE-vo', 'objective; target'),
    ('obbligo', 'OHB-blee-goh', 'obligation; duty'),
    ('obietta', 'oh-BYET-tah', 'objects'),
    ('obietti', 'oh-BYET-tee', 'you object'),
    ('obiettivi', 'oh-byeht-TEE-vee', 'objectives; goals'),
    ('obiettivo', 'oh-byeht-TEE-vo', 'objective; target'),
    ('obiezione', 'oh-byeht-TZOH-neh', 'objection'),
    ('obiezioni', 'oh-byeht-TZOH-nee', 'objections'),
    ('obitorio', 'oh-bee-TOH-ryoh', 'morgue'),
    ('oca', 'OH-kah', 'goose'),
    ('ocarina', 'oh-kah-REE-nah', 'ocarina'),
    ('occasione', 'oh-kah-ZYOH-neh', 'occasion; chance'),
    ('occasioni', 'oh-kah-ZYOH-nee', 'occasions; chances'),
    ('occhiata', 'ohk-YAH-tah', 'glance; look'),
    ('occhiello', 'ohk-YEHL-lo', 'buttonhole; loop'),
    ('occhiolino', 'ohk-kyoh-LEE-no', 'wink'),
    ('occupazione', 'ohk-koo-pah-TZOH-neh', 'occupation; job'),
    ('oceani', 'oh-CHAY-ah-nee', 'oceans'),
    ('oceano', 'oh-CHAY-ah-no', 'ocean'),
    ('oceanografo', 'oh-cheh-ah-NOH-grah-fo', 'oceanographer'),
    ('oculista', 'oh-koo-LEE-stah', 'eye doctor'),
    ('odio', 'OH-dyoh', 'hatred'),
    ('odontoiatria', 'oh-dohn-toh-yah-TREE-ah', 'dentistry'),
    ('odora', 'oh-DOH-rah', 'smells'),
    ('offesa', 'oh-FAY-zah', 'offense; insult'),
    ('offese', 'oh-FAY-zeh', 'offenses; insults'),
    ('officina', 'ohf-fee-CHEE-nah', 'workshop; repair shop'),
    ('offrirti', 'oh-FREER-tee', 'to offer you'),
    ('oftalmologo', 'ohf-tahl-MOH-loh-goh', 'ophthalmologist'),
    ('oggetti', 'ohj-JET-tee', 'objects; items'),
    ('oggetto', 'ohj-JET-toh', 'object; item'),
    ('oggi', 'OHJ-jee', 'today'),
    ('oh', 'oh', 'oh'),
    ('okapi', 'OH-kah-pee', 'okapi'),
    ('olandese', 'oh-lahn-DAY-zeh', 'Dutch person; Dutch (language)'),
    ('olandesi', 'oh-lahn-DAY-zee', 'Dutch people'),
    ('olfatto', 'ohl-FAHT-toh', 'sense of smell'),
    ('oli', 'OH-lee', 'oils'),
    ('olio', 'OH-lyoh', 'oil'),
    ('olocausto', 'oh-loh-COW-stoh', 'holocaust'),
    ('ologrammi', 'oh-loh-GRAHM-mee', 'holograms'),
    ('oltraggio', 'ohl-TRAHJ-joh', 'outrage; affront'),
    ('omaggio', 'oh-MAHJ-joh', 'tribute; complimentary gift'),
    ('ombelico', 'ohm-beh-LEE-koh', 'navel; belly button'),
    ('ombra', 'OHM-brah', 'shadow; shade'),
    ('ombre', 'OHM-breh', 'shadows; shades'),
    ('ombrellata', 'ohm-brehl-LAH-tah', 'umbrella blow'),
    ('omelette', 'oh-meh-LEHT-teh', 'omelets'),
    ('omeomorfismo', 'oh-meh-oh-mor-FEES-moh', 'homeomorphism'),
    ('omicida', 'oh-mee-CHEE-dah', 'murderer'),
    ('omicidi', 'oh-mee-CHEE-dee', 'murders; homicides'),
    ('omicidio', 'oh-mee-CHEE-dyoh', 'murder; homicide'),
    ('omidicio', 'oh-mee-DEE-chyoh', 'murder'),
    ('omofobi', 'oh-moh-FOH-bee', 'homophobes'),
    ('omofobia', 'oh-moh-FOH-byah', 'homophobia'),
    ('omofobo', 'oh-moh-FOH-boh', 'homophobe'),
    ('omofoni', 'oh-moh-FOH-nee', 'homophones'),
    ('omomorfismo', 'oh-moh-mor-FEES-moh', 'homomorphism'),
    ('omosessuale', 'oh-moh-ses-SWAH-leh', 'homosexual'),
    ('omuncoli', 'oh-MOON-koh-lee', 'little men; runts'),
    ('oncie', 'OHN-chay', 'ounces'),
    ('onda', 'OHN-dah', 'wave'),
    ('ondate', 'ohn-DAH-teh', 'surges; waves'),
    ('onde', 'OHN-deh', 'waves'),
    ('oneri', 'OH-neh-ree', 'burdens; charges'),
    ('onesti', 'oh-NES-tee', 'honest people'),
    ('onestà', 'oh-nes-TAH', 'honesty'),
    ('onor', 'oh-NOHR', 'honor'),
    ('onore', 'oh-NOH-reh', 'honor'),
    ('onorificenza', 'oh-noh-ree-fee-CHEN-tsah', 'honorific award'),
    ('opera', 'OH-peh-rah', 'opera; work'),
    ('operai', 'oh-peh-RAH-ee', 'workers (masculine)'),
    ('operaia', 'oh-peh-RAH-yah', 'worker (feminine)'),
    ('operaio', 'oh-peh-RAH-yoh', 'worker (masculine)'),
    ('operatore', 'oh-peh-rah-TOH-reh', 'operator'),
    ('operazione', 'oh-peh-rah-TSYOH-neh', 'operation; surgery'),
    ('operazioni', 'oh-peh-rah-TSYOH-nee', 'operations; procedures'),
    ('opere', 'OH-peh-reh', 'works; operas'),
    ('operetta', 'oh-peh-REHT-tah', 'operetta'),
    ('opossum', 'oh-POHS-soom', 'opossum'),
    ('oppio', 'OPP-yoh', 'opium'),
    ('opporsi', 'ohp-POR-see', 'to oppose'),
    ('opportunità', 'oh-por-too-nee-TAH', 'opportunity'),
    ('opposizione', 'ohp-poh-zee-TZOH-neh', 'opposition'),
    ('opposto', 'ohp-POS-toh', 'opposite'),
    ('oppressione', 'ohp-pres-SYOH-neh', 'oppression'),
    ('opuscoli', 'oh-POOS-koh-lee', 'pamphlets; brochures'),
    ('opzione', 'op-TZOH-neh', 'option'),
    ('opzioni', 'op-TZOH-nee', 'options'),
    ('orafo', 'OH-rah-foh', 'goldsmith'),
    ('orali', 'oh-RAH-lee', 'oral exams'),
    ('oratore', 'oh-rah-TOH-reh', 'speaker (masculine)'),
    ('oratrice', 'oh-rah-TREE-cheh', 'speaker (feminine)'),
    ('orazione', 'oh-rah-TSYOH-neh', 'oration; speech'),
    ('orazioni', 'oh-rah-TSYOH-nee', 'orations; speeches'),
    ('orbita', 'OR-bee-tah', 'orbit'),
    ('orbite', 'OR-bee-teh', 'orbits'),
    ('orchestra', 'or-KEHS-trah', 'orchestra'),
    ('orchidee', 'or-kee-DAY-eh', 'orchids'),
    ('orecchi', 'oh-REK-kee', 'ears'),
    ('orecchie', 'oh-REK-kyeh', 'ears'),
    ('orecchini', 'oh-rek-KEE-nee', 'earrings'),
    ('orecchino', 'oh-rek-KEE-noh', 'earring'),
    ('orecchio', 'oh-REK-kyoh', 'ear'),
    ('orfana', 'OR-fah-nah', 'orphan (feminine)'),
    ('orfani', 'OR-fah-nee', 'orphans (masculine)'),
    ('orfano', 'OR-fah-noh', 'orphan (masculine)'),
    ('orfanotrofio', 'or-fah-no-TROH-fyoh', 'orphanage'),
    ('org', 'dot-ORG', 'dot-org domain'),
    ('organi', 'OR-gah-nee', 'organs'),
    ('organismo', 'or-gah-NEEZ-moh', 'organism'),
    ('organizzazione', 'or-gahn-nid-zah-TZOH-neh', 'organization'),
    ('organizzazioni', 'or-gahn-nid-zah-TZOH-nee', 'organizations'),
    ('organo', 'OR-gah-noh', 'organ'),
    ('orgasmi', 'or-GAHS-mee', 'orgasms'),
    ('orgia', 'OR-jah', 'orgy'),
    ('orgoglio', 'or-GOH-lyoh', 'pride'),
    ('orgogliosi', 'or-goh-LYOH-zee', 'proud people'),
    ('orientamenti', 'oh-ree-en-tah-MEN-tee', 'orientations; guidelines'),
    ('orientamento', 'oh-ree-en-tah-MEN-toh', 'orientation'),
    ('orienteering', 'oh-ree-en-TEER-ing', 'orienteering'),
    ('originale', 'oh-ree-jee-NAH-leh', 'original; master copy'),
    ('origine', 'oh-REE-jee-neh', 'origin'),
    ('origini', 'oh-REE-jee-nee', 'origins'),
    ('oritteropi', 'oh-ree-TEH-roh-pee', 'aardvarks'),
    ('oritteropo', 'oh-ree-TEH-roh-poh', 'aardvark'),
    ('orizzonte', 'oh-ree-DZON-teh', 'horizon'),
    ('orizzonti', 'oh-ree-DZON-tee', 'horizons'),
    ('orlo', 'OR-loh', 'hem; edge'),
    ('orme', 'OR-meh', 'footprints'),
    ('ormoni', 'or-MOH-nee', 'hormones'),
    ('oroscopo', 'oh-ROH-skoh-poh', 'horoscope'),
    ('orrore', 'oh-ROH-reh', 'horror'),
    ('orsacchiotto', 'or-sahk-KYOT-toh', 'teddy bear'),
    ('orsetto', 'or-SET-toh', 'little bear; teddy'),
    ('orsi', 'OR-see', 'bears'),
    ('orso', 'OR-soh', 'bear'),
    ('ortaggi', 'or-TAH-jee', 'vegetables'),
    ('ortaggio', 'or-TAH-joh', 'vegetable'),
    ('orto', 'OR-toh', 'vegetable garden'),
    ('ortodontista', 'or-toh-dohn-TEEN-stah', 'orthodontist'),
    ('ortografia', 'or-toh-grah-FEE-ah', 'orthography; spelling'),
    ('orzaiolo', 'or-dzah-YOH-loh', 'stye'),
    ('oscillazioni', 'oh-sheel-lah-TZOH-nee', 'oscillations; mood swings'),
    ('oscurità', 'oh-skoo-ree-TAH', 'darkness'),
    ('oscuro', 'oh-SKOO-roh', 'darkness'),
    ('osmosi', 'ohz-MOH-zee', 'osmosis'),
    ('ospitalità', 'oh-spee-tah-lee-TAH', 'hospitality'),
    ('ospite', 'OS-pee-teh', 'guest'),
    ('ospiti', 'OS-pee-tee', 'guests'),
    ('ossa', 'OSS-sah', 'bones'),
    ('osservanza', 'ohs-sehr-VAHN-tsah', 'observance'),
    ('osservatorio', 'ohs-sehr-vah-TOR-ryoh', 'observatory'),
    ('osservazione', 'ohs-sehr-vah-TZOH-neh', 'observation'),
    ('osservazioni', 'ohs-sehr-vah-TZOH-nee', 'observations; remarks'),
    ('ossessione', 'ohs-ses-SYOH-neh', 'obsession'),
    ('ossigeno', 'ohs-SEE-jeh-noh', 'oxygen'),
    ('ossimoro', 'ohs-SEE-moh-roh', 'oxymoron'),
    ('osso', 'OSS-soh', 'bone'),
    ('ostacoli', 'ohs-TAH-koh-lee', 'obstacles'),
    ('ostacolo', 'ohs-TAH-koh-loh', 'obstacle'),
    ('ostaggi', 'ohs-TAH-jee', 'hostages'),
    ('ostaggio', 'ohs-TAH-joh', 'hostage'),
    ('ostello', 'ohs-TEL-loh', 'hostel'),
    ('osteoporosi', 'ohs-teh-oh-poh-ROH-zee', 'osteoporosis'),
    ('ostilità', 'ohs-tee-lee-TAH', 'hostility'),
    ('ostriche', 'ohs-TREE-keh', 'oysters'),
    ('otoshidama', 'oh-toh-shee-DAH-mah', "New Year's gift (otoshidama)"),
    ('ottavino', 'ot-tah-VEE-noh', 'piccolo'),
    ('ottavo', 'ot-TAH-voh', 'eighth'),
    ('ottica', 'OT-tee-kah', 'optics shop; eyewear store'),
    ('ottimismo', 'ot-tee-MEES-moh', 'optimism'),
    ('ottimista', 'ot-tee-MEES-tah', 'optimist'),
    ('ottobre', 'ot-TOH-breh', 'october'),
    ('ottone', 'ot-TOH-neh', 'brass'),
    ('ottoni', 'ot-TOH-nee', 'brass instruments'),
    ('outing', 'OW-ting', 'coming out'),
    ('ovaie', 'oh-VAH-yeh', 'ovaries'),
    ('over', 'OH-ver', 'over (older than)'),
    ('overdose', 'OH-ver-doh-zay', 'overdose'),
    ('ovest', 'OH-vest', 'west'),
    ('ovulazione', 'oh-voo-lah-TZOH-neh', 'ovulation'),
    ('ovulo', 'OH-voo-loh', 'ovum; egg cell'),
    ('ovvio', 'OHV-vyoh', 'obvious fact'),
    ('ozio', 'OH-dzyoh', 'idleness'),
    ('oziosi', 'oh-DZYO-zee', 'idle people'),
    ('ozono', 'oh-ZOH-noh', 'ozone'),
]

data = {text: (pron, translation) for text, pron, translation in DATA}

files = [f for f in os.listdir(BASE_DIR) if f.lower().startswith('o') and f.endswith('.tsv')]
updated_files = []
for fname in files:
    path = os.path.join(BASE_DIR, fname)
    with open(path, newline='') as fh:
        rows = list(csv.DictReader(fh, delimiter='\t'))
    changed = False
    for row in rows:
        key = row['text']
        if key not in data:
            continue
        pronunciation, translation = data[key]
        if not row['pronunciation'].strip() and pronunciation:
            row['pronunciation'] = pronunciation
            changed = True
        if not row['translation_en'].strip() and translation:
            row['translation_en'] = translation
            changed = True
    if changed:
        with open(path, 'w', newline='') as fh:
            writer = csv.DictWriter(fh, fieldnames=rows[0].keys(), delimiter='\t')
            writer.writeheader()
            writer.writerows(rows)
        updated_files.append(fname)

print(f"Updated {len(updated_files)} files")
