import pandas as pd
from pathlib import Path

lemma_senses = {
    'sdegnoso': 'disdainful; scornful',
    'sdentato': 'toothless',
    'sdraiato': 'lying down; sprawled',
    'secca': 'dry',
    'seccante': 'annoying; tiresome',
    'secchio': 'bucket-like; pail-shaped',
    'secco': 'dry; arid; skinny',
    'secondario': 'secondary; minor',
    'sedicesimo': 'sixteenth',
    'sedimentario': 'sedimentary',
    'seducente': 'seductive; alluring',
    'segreto': 'secret; confidential',
    'seguente': 'following; next',
    'selvaggio': 'wild; savage',
    'selvatico': 'wild; untamed',
    'semantico': 'semantic',
    'sempliciotto': 'simple-minded; gullible',
    'semplificato': 'simplified; streamlined',
    'sensato': 'sensible; reasonable',
    'sensazionale': 'sensational; amazing',
    'sensibile': 'sensitive; responsive',
    'sensitivo': 'sensitive; psychic',
    'sensoriale': 'sensory',
    'sentimentale': 'sentimental; romantic',
    'sentire': 'heartfelt; sincere',
    'senziente': 'sentient',
    'separato': 'separate; separated',
    'serale': 'evening; nightly',
    'serbo': 'Serbian',
    'sereno': 'calm; serene; peaceful',
    'seriale': 'serial',
    'serissimo': 'very serious; deadly serious',
    'sero': 'very serious; deadly serious',
    'serrata': 'tight; shut; sealed',
    'servito': 'served',
    'sessantenne': 'sixty-year-old',
    'sessista': 'sexist',
    'sessuale': 'sexual',
    'sesto': 'sixth',
    'settario': 'sectarian; fanatical',
    'settentrionale': 'northern',
    'settimanale': 'weekly',
    'settimo': 'seventh',
    'severo': 'strict; severe',
    'sexy': 'sexy',
    'sfacciato': 'shameless; cheeky',
    'sfarzoso': 'lavish; sumptuous',
    'sfiancato': 'exhausted; worn-out',
    'sfibrante': 'draining; exhausting',
    'sfortunato': 'unlucky; unfortunate',
    'sgarbato': 'rude; impolite',
    'sgargiante': 'gaudy; flashy',
    'sghignazzato': 'snickering; giggling',
    'sgonfiare': 'flat; deflated',
    'sgradevole': 'unpleasant; disagreeable',
    'sgrammaticato': 'ungrammatical; illiterate',
    'shanghainese': 'Shanghainese',
    'shintoista': 'Shinto; Shintoist',
    'siberiano': 'Siberian',
    'siciliano': 'Sicilian',
    'siedito': 'sit down; take a seat',
    'sieropositivo': 'HIV-positive; seropositive',
    'significativo': 'significant; meaningful',
    'silenzioso': 'quiet; silent',
    'simbolico': 'symbolic',
    'simbolo': 'symbol',
    'simile': 'similar; alike',
    'simmetrico': 'symmetrical',
    'simpatico': 'nice; friendly; likable',
    'simultaneo': 'simultaneous; concurrent',
    'sincero': 'sincere; honest',
    'singaporiano': 'Singaporean',
    'single': 'single',
    'singolare': 'singular; unusual',
    'singolo': 'single; individual',
    'sinistro': 'left; sinister',
    'sinonimo': 'synonymous; equivalent',
    'sintetico': 'synthetic; concise',
    'siriano': 'Syrian',
    'slacciato': 'unfastened; undone',
    'slanciato': 'slender; lanky',
    'sleale': 'disloyal; unfair',
    'smarrire': 'lost; missing',
    'smarrito': 'lost; missing',
    'smemorato': 'forgetful; absent-minded',
    'smilzo': 'skinny; scrawny',
    'snello': 'slim; slender',
    'sobrio': 'sober; restrained',
    'socchiuso': 'half-closed; ajar',
    'sociale': 'social',
    'socialista': 'socialist',
    'socievo': 'sociable; outgoing',
    'socievole': 'sociable; friendly',
    'sociopatico': 'sociopathic',
    'soddisfacente': 'satisfactory; rewarding',
    'soddisfare': 'satisfied; content',
    'soddisfatto': 'satisfied; pleased',
    'soddisfattto': 'satisfied; pleased',
    'sode': 'hard-boiled; firm',
    'sodo': 'solid; firm; hard-boiled',
    'soffice': 'soft; fluffy',
    'soffico': 'soft; velvety',
    'soffocante': 'suffocating; stifling',
    'sofisticato': 'sophisticated; refined',
    'sofistico': 'sophistic; specious',
    'sofà': 'sofa-like',
    'soggettivo': 'subjective',
    'soggetto': 'subject; liable',
    'solare': 'solar; sunny; cheerful',
    'soleggiato': 'sunny; sunlit',
    'solenne': 'solemn; stately',
    'solerto': 'diligent; prompt',
    'solido': 'solid; sturdy',
    'solitario': 'lonely; solitary',
    'solito': 'usual; customary',
    'solubile': 'soluble',
    'somigliante': 'resembling; similar',
    'sommare': 'summed up; taken together',
    'sommerso': 'submerged; hidden',
    'sonnolente': 'sleepy; drowsy',
    'sonore': 'sonorous; sound',
    'sopportabile': 'bearable; tolerable',
    'sopraddetto': 'aforementioned; aforesaid',
    'soprannaturale': 'supernatural',
    'sordo': 'deaf',
    'sorella': 'sisterly; like sisters',
    'sorgente': 'spring-like; source',
    'sorpredente': 'surprising; amazing',
    'sorprendente': 'surprising; astonishing',
    'sorprendere': 'surprised',
    'sorpresa': 'surprised',
    'sorpreso': 'surprised',
    'sorridente': 'smiling; cheerful',
    'sospeso': 'suspended; pending',
    'sospetto': 'suspicious; suspect',
    'sospettoso': 'suspicious; distrustful',
    'sostanziale': 'substantial; essential',
    'sostanzioso': 'hearty; substantial',
    'sostenibile': 'sustainable',
    'sostituibile': 'replaceable',
    'sottile': 'thin; subtle',
    'sottintese': 'implied; unspoken',
    'sottobanco': 'under the table; illicit',
    'sottolineare': 'underlined; emphasized',
    'sottopeso': 'underweight',
    'sottosopro': 'upside down; in disarray',
    'sottotitolato': 'subtitled',
    'sottovalutare': 'underestimated',
    'sovietico': 'Soviet',
    'sovraccarico': 'overloaded; overburdened',
    'sovrano': 'sovereign; supreme',
    'sovrappeso': 'overweight',
    'sovvrappeso': 'overweight',
    'spagnolo': 'Spanish',
    'spaiato': 'mismatched; odd',
    'sparire': 'gone; missing',
    'sparso': 'scattered; sparse',
    'spassoso': 'funny; amusing',
    'spaventato': 'frightened; scared',
    'spaventoso': 'frightening; scary',
    'spaziale': 'space-related; cosmic',
    'spazioso': 'spacious; roomy',
    'spazzaturo': 'trash; garbage',
    'speciale': 'special',
    'specialistico': 'specialist; specialized',
    'specializzato': 'specialized; trained',
    'specificato': 'specified; stated',
    'specifico': 'specific; particular',
    'spediscilo': 'send it',
    'spegnere': 'off; extinguished',
    'spensierato': 'carefree; lighthearted',
    'spente': 'dim; extinguished',
    'spento': 'off; dull',
    'sperduto': 'lost; remote',
    'sperimentale': 'experimental',
    'spesso': 'thick; dense',
    'spettacolare': 'spectacular; amazing',
    'spettinato': 'unkempt; tousled',
    'spezzare': 'broken; snapped',
    'spiacente': 'sorry; regretful',
    'spiacevole': 'unpleasant; regrettable',
    'spiccato': 'pronounced; marked',
    'spiegazzato': 'wrinkled; crumpled',
    'spietato': 'ruthless; merciless',
    'spinoso': 'thorny; prickly',
    'spiritoso': 'witty; funny',
    'spirituale': 'spiritual',
    'splendido': 'splendid; gorgeous',
    'spocchioso': 'snobbish; arrogant',
    'spoglio': 'bare; stripped',
    'spompato': 'exhausted; spent',
    'spontaneo': 'spontaneous',
    'sporadico': 'sporadic; occasional',
    'sporco': 'dirty; filthy',
    'sportivo': 'sporty; athletic',
    'sposare': 'married',
    'sposato': 'married',
    'sposino': 'newlywed; bride-and-groom',
    'spossante': 'exhausting; draining',
    'spossato': 'exhausted; drained',
    'sprecare': 'wasted; squandered',
    'spregevole': 'despicable; contemptible',
    'spregiudicato': 'uninhibited; unprincipled',
    'sprezzante': 'scornful; disdainful',
    'squallido': 'squalid; shabby',
    'squilibrato': 'unbalanced; unstable',
    'squisito': 'delicious; exquisite',
    'stabile': 'stable; steady',
    'stabilire': 'established; set',
    'stagionale': 'seasonal',
    'stagnante': 'stagnant; sluggish',
    'stampare': 'printed',
    'stancante': 'tiring; exhausting',
    'standard': 'standard',
    'stanotte': 'tonight',
    'stantio': 'stale; musty',
    'starnutì': 'sneezed',
    'statale': 'state-run; public',
    'statistico': 'statistical',
    'statunitense': 'American; U.S.',
    'stentato': 'halting; labored',
    'stereo': 'stereo',
    'sterile': 'sterile; barren',
    'stimolante': 'stimulating; inspiring',
    'stomachevole': 'nauseating; sickening',
    'stonato': 'off-key; tuneless',
    'stordito': 'dazed; stunned',
    'storico': 'historic; historical',
    'storto': 'crooked; warped',
    'strabico': 'cross-eyed',
    'stradale': 'road; street',
    'stragrande': 'vast; overwhelming',
    'strambio': 'odd; quirky',
    'strambo': 'weird; eccentric',
    'strampalato': 'bizarre; far-fetched',
    'straordinario': 'extraordinary; outstanding',
    'strapazzato': 'overworked; beaten up',
    'strappalaceime': 'tear-jerking; heart-wrenching',
    'stravagante': 'extravagant; eccentric',
    'straziante': 'heartbreaking; agonizing',
    'stregato': 'bewitched; enchanted',
    'stremato': 'exhausted; spent',
    'strepitoso': 'amazing; terrific',
    'stressante': 'stressful',
    'stressare': 'stressed out; under stress',
    'stressati': 'stressed; tense',
    'stressato': 'stressed; tense',
    'stretto': 'tight; narrow',
    'stridulo': 'shrill; squeaky',
    'strumentale': 'instrumental',
    'studente': 'student-related',
    'studentesco': 'student; collegiate',
    'stufo': 'fed up; sick of it',
    'stupefatto': 'astonished; amazed',
    'stupendo': 'wonderful; amazing',
    'stupidotto': 'pretty stupid; dim',
    'stupito': 'surprised; amazed',
}

pronunciations = {
    'sdegnoso': 'zdeh-NYOH-soh',
    'sdentato': 'zdehn-TAH-toh',
    'sdraiata': 'zdrah-YAH-tah',
    'sdraiato': 'zdrah-YAH-toh',
    'secche': 'SEHK-keh',
    'seccanti': 'sehk-KAHN-tee',
    'secchio': 'SEHK-kyoh',
    'secca': 'SEHK-kah',
    'secchi': 'SEHK-kee',
    'secco': 'SEHK-koh',
    'secondari': 'seh-kohn-DAH-ree',
    'secondaria': 'seh-kohn-DAH-ryah',
    'sedicesimo': 'seh-dee-CHAY-zee-moh',
    'sedimentaria': 'seh-dee-men-TAH-ryah',
    'seducente': 'seh-doo-CHEN-teh',
    'segreta': 'seh-GREH-tah',
    'segrete': 'seh-GREH-teh',
    'segreti': 'seh-GREH-tee',
    'segreto': 'seh-GREH-toh',
    'seguente': 'seh-GWEN-teh',
    'seguenti': 'seh-GWEN-tee',
    'selvagge': 'sehl-VAHJ-jeh',
    'selvaggi': 'sehl-VAHJ-jee',
    'selvaggia': 'sehl-VAHJ-jah',
    'selvaggio': 'sehl-VAHJ-joh',
    'selvatici': 'sehl-VAH-tee-chee',
    'semantica': 'seh-MAHN-tee-kah',
    'sempliciotta': 'sehm-plee-CHOHT-tah',
    'sempliciotto': 'sehm-plee-CHOHT-toh',
    'semplificato': 'sehm-plee-fee-KAH-toh',
    'sensata': 'sehn-SAH-tah',
    'sensate': 'sehn-SAH-teh',
    'sensato': 'sehn-SAH-toh',
    'sensazionale': 'sehn-sah-tsee-oh-NAH-leh',
    'sensibile': 'sehn-SEE-bee-leh',
    'sensibili': 'sehn-SEE-bee-lee',
    'sensitiva': 'sehn-see-TEE-vah',
    'sensoriali': 'sehn-soh-ryAH-lee',
    'sentimentale': 'sehn-tee-men-TAH-leh',
    'sentimentali': 'sehn-tee-men-TAH-lee',
    'sentite': 'sehn-TEE-teh',
    'senzienti': 'sehn-TSYEN-tee',
    'separate': 'seh-pah-RAH-teh',
    'separati': 'seh-pah-RAH-tee',
    'serale': 'seh-RAH-leh',
    'serbe': 'SEHR-beh',
    'serbi': 'SEHR-bee',
    'serena': 'seh-RAY-nah',
    'seriale': 'seh-ree-AH-leh',
    'serissimo': 'seh-REE-see-moh',
    'serissima': 'seh-REE-see-mah',
    'serrate': 'sehr-RAH-teh',
    'servite': 'sehr-VEE-teh',
    'sessantenne': 'seh-sahn-TEHN-neh',
    'sessista': 'seh-SEES-tah',
    'sessuale': 'seh-soo-AH-leh',
    'sessuali': 'seh-soo-AH-lee',
    'sesto': 'SEHS-toh',
    'settaria': 'seht-TAH-ryah',
    'settentrionale': 'seht-tehn-tree-oh-NAH-leh',
    'settimanale': 'seht-tee-mah-NAH-leh',
    'settimo': 'SEHT-tee-moh',
    'severa': 'seh-VEH-rah',
    'severe': 'seh-VEH-reh',
    'severi': 'seh-VEH-ree',
    'severo': 'seh-VEH-roh',
    'sexy': 'SEHK-see',
    'sfacciata': 'sfah-CHAH-tah',
    'sfacciato': 'sfah-CHAH-toh',
    'sfarzoso': 'sfahr-ZOH-zoh',
    'sfiancata': 'sfee-ahn-KAH-tah',
    'sfibrante': 'sfee-BRAHN-teh',
    'sfortunata': 'sfor-too-NAH-tah',
    'sfortunato': 'sfor-too-NAH-toh',
    'sgarbata': 'sgahr-BAH-tah',
    'sgarbati': 'sgahr-BAH-tee',
    'sgarbato': 'sgahr-BAH-toh',
    'sgargiante': 'sgahr-JAHN-teh',
    'sgargianti': 'sgahr-JAHN-tee',
    'sghignazzate': 'sgee-nyah-TSAH-teh',
    'sgonfia': 'SGOHN-fyah',
    'sgradevole': 'sgrah-DEH-voh-leh',
    'sgrammaticato': 'sgrahm-mah-tee-KAH-toh',
    'shanghainese': 'shahn-guy-NEH-zeh',
    'shintoista': 'sheen-toh-EES-tah',
    'siberiana': 'see-beh-ryAH-nah',
    'siberiane': 'see-beh-ryAH-neh',
    'siciliane': 'see-chee-LYAH-neh',
    'siciliano': 'see-chee-LYAH-noh',
    'siediti': 'SYEH-dee-tee',
    'sieropositiva': 'syeh-roh-poh-zee-TEE-vah',
    'significativa': 'see-nyee-fee-kah-TEE-vah',
    'significative': 'see-nyee-fee-kah-TEE-veh',
    'significativo': 'see-nyee-fee-kah-TEE-voh',
    'silenziosa': 'see-len-TZOH-zah',
    'silenziosi': 'see-len-TZOH-zee',
    'silenzioso': 'see-len-TZOH-zoh',
    'simbolico': 'seem-BOH-lee-koh',
    'simbolo': 'SEEM-boh-loh',
    'simile': 'SEE-mee-leh',
    'simili': 'SEE-mee-lee',
    'simmetrica': 'seem-MEH-tree-kah',
    'simpatica': 'seem-PAH-tee-kah',
    'simpatiche': 'seem-PAH-tee-keh',
    'simpatici': 'seem-PAH-tee-chee',
    'simpatico': 'seem-PAH-tee-koh',
    'simultaneo': 'see-mool-TAH-neh-oh',
    'sincera': 'seen-CHEH-rah',
    'sincere': 'seen-CHEH-reh',
    'sinceri': 'seen-CHEH-ree',
    'sincero': 'seen-CHEH-roh',
    'singaporiana': 'seen-gah-poh-ryAH-nah',
    'single': 'SEEN-guhl',
    'singolare': 'seen-goh-LAH-reh',
    'singola': 'SEEN-goh-lah',
    'singole': 'SEEN-goh-leh',
    'singolo': 'SEEN-goh-loh',
    'sinistra': 'see-NEES-trah',
    'sinistro': 'see-NEES-troh',
    'sinonimo': 'see-NOH-nee-moh',
    'sintetica': 'seen-TEH-tee-kah',
    'siriana': 'see-ree-AH-nah',
    'slacciate': 'slah-CHAH-teh',
    'slanciata': 'slahn-CHAH-tah',
    'sleali': 'slay-AH-lee',
    'smarrito': 'smar-REE-toh',
    'smarriti': 'smar-REE-tee',
    'smemorata': 'smay-moh-RAH-tah',
    'smemorato': 'smay-moh-RAH-toh',
    'smilzo': 'SMEEL-tsoh',
    'snello': 'SNEHL-loh',
    'sobri': 'SOH-bree',
    'sobria': 'SOH-bryah',
    'sobrio': 'SOH-bryoh',
    'socchiuso': 'sohk-KYOO-zoh',
    'social': 'soh-CHAHL',
    'sociale': 'soh-CHAH-leh',
    'sociali': 'soh-CHAH-lee',
    'socialiste': 'soh-chah-LEES-teh',
    'socievole': 'soh-CHEH-voh-leh',
    'sociopatico': 'soh-chyo-PAH-tee-koh',
    'soddisfacente': 'soh-dees-fah-CHEN-teh',
    'soddisfacenti': 'soh-dees-fah-CHEN-tee',
    'soddisfatte': 'soh-dees-FAHT-teh',
    'soddisfatta': 'soh-dees-FAHT-tah',
    'soddisfatti': 'soh-dees-FAHT-tee',
    'soddisfatto': 'soh-dees-FAHT-toh',
    'soddisfattti': 'soh-dees-FAHT-tee',
    'sode': 'SOH-deh',
    'sodo': 'SOH-doh',
    'soffice': 'SOH-fee-cheh',
    'soffici': 'SOH-fee-chee',
    'soffocante': 'soh-foh-KAHN-teh',
    'sofisticata': 'soh-fee-stee-KAH-tah',
    'sofisticati': 'soh-fee-stee-KAH-tee',
    'sofisticato': 'soh-fee-stee-KAH-toh',
    'sofistica': 'soh-FEES-tee-kah',
    'sofà': 'soh-FAH',
    'soggettiva': 'sohj-jeh-TEE-vah',
    'soggettivo': 'sohj-jeh-TEE-voh',
    'soggetta': 'sohj-JEHT-tah',
    'soggetti': 'sohj-JEHT-tee',
    'soggetto': 'sohj-JEHT-toh',
    'solare': 'soh-LAH-reh',
    'solari': 'soh-LAH-ree',
    'soleggiata': 'soh-lehj-JAH-tah',
    'soleggiato': 'soh-lehj-JAH-toh',
    'solenne': 'soh-LEHN-neh',
    'solerte': 'soh-LEHR-teh',
    'solida': 'SOH-lee-dah',
    'solide': 'SOH-lee-deh',
    'solidi': 'SOH-lee-dee',
    'solido': 'SOH-lee-doh',
    'solitari': 'soh-lee-TAH-ree',
    'solitaria': 'soh-lee-TAH-ryah',
    'solitario': 'soh-lee-TAH-ryoh',
    'solita': 'SOH-lee-tah',
    'solito': 'SOH-lee-toh',
    'solubile': 'soh-LOO-bee-leh',
    'somigliante': 'soh-mee-LYAHN-teh',
    'sommato': 'sohm-MAH-toh',
    'sommersa': 'sohm-MEHR-sah',
    'sonnolenti': 'sohn-noh-LEHN-tee',
    'sonore': 'soh-NOH-reh',
    'sopportabile': 'sohp-por-TAH-bee-leh',
    'sopraddette': 'soh-prahd-DEHT-teh',
    'soprannaturali': 'soh-prah-nah-too-RAH-lee',
    'sorda': 'SOR-dah',
    'sorde': 'SOR-deh',
    'sordi': 'SOR-dee',
    'sordo': 'SOR-doh',
    'sorelle': 'soh-REHL-leh',
    'sorgente': 'sohr-JEN-teh',
    'sorpredente': 'sohr-preh-DEN-teh',
    'sorprendente': 'sohr-prehn-DEN-teh',
    'sorprendenti': 'sohr-prehn-DEN-tee',
    'sorpresi': 'sohr-PREH-zee',
    'sorpresa': 'sohr-PREH-zah',
    'sorprese': 'sohr-PREH-zeh',
    'sorpreso': 'sohr-PREH-zoh',
    'sorridente': 'soh-ree-DEN-teh',
    'sorridenti': 'soh-ree-DEN-tee',
    'sospeso': 'sohs-PAY-zoh',
    'sospetta': 'sohs-PEHT-tah',
    'sospette': 'sohs-PEHT-teh',
    'sospetti': 'sohs-PEHT-tee',
    'sospetto': 'sohs-PEHT-toh',
    'sospettosa': 'sohs-peht-TOH-zah',
    'sospettose': 'sohs-peht-TOH-zeh',
    'sospettosi': 'sohs-peht-TOH-zee',
    'sospettoso': 'sohs-peht-TOH-zoh',
    'sostanziale': 'sohs-tahn-TSYAH-leh',
    'sostanzioso': 'sohs-tahn-TZOH-zoh',
    'sostenibile': 'sohs-teh-NEE-bee-leh',
    'sostenibili': 'sohs-teh-NEE-bee-lee',
    'sostituibile': 'sohs-tee-too-EE-bee-leh',
    'sottile': 'soh-TEE-leh',
    'sottili': 'soh-TEE-lee',
    'sottintese': 'soht-teen-TEH-seh',
    'sottobanco': 'soht-toh-BAHN-koh',
    'sottolineate': 'soht-toh-lee-neh-AH-teh',
    'sottopeso': 'soht-toh-PAY-zoh',
    'sottosopra': 'soht-toh-SOH-prah',
    'sottotitolata': 'soht-toh-tee-toh-LAH-tah',
    'sottovalutato': 'soht-toh-vah-loo-TAH-toh',
    'sovietica': 'soh-VYAY-tee-kah',
    'sovietiche': 'soh-VYAY-tee-keh',
    'sovietico': 'soh-VYAY-tee-koh',
    'sovraccarico': 'sohv-rahk-KAH-ree-koh',
    'sovrana': 'soh-VRAH-nah',
    'sovrano': 'soh-VRAH-noh',
    'sovrappeso': 'sohv-rahp-PAY-zoh',
    'sovvrappeso': 'sohv-rahp-PAY-zoh',
    'spagnola': 'spahn-YOH-lah',
    'spagnole': 'spahn-YOH-leh',
    'spagnoli': 'spahn-YOH-lee',
    'spagnolo': 'spahn-YOH-loh',
    'spaiate': 'spah-YAH-teh',
    'sparita': 'spah-REE-tah',
    'spariti': 'spah-REE-tee',
    'sparsi': 'SPAR-see',
    'spassoso': 'spah-SOH-zoh',
    'spaventata': 'spah-vehn-TAH-tah',
    'spaventati': 'spah-vehn-TAH-tee',
    'spaventato': 'spah-vehn-TAH-toh',
    'spaventosa': 'spah-vehn-TOH-zah',
    'spaventose': 'spah-vehn-TOH-zeh',
    'spaventoso': 'spah-vehn-TOH-zoh',
    'spaziale': 'spah-TSYAH-leh',
    'spaziali': 'spah-TSYAH-lee',
    'spazioso': 'spah-TZOH-zoh',
    'spazzatura': 'spahz-zah-TOO-rah',
    'speciale': 'speh-CHAH-leh',
    'speciali': 'speh-CHAH-lee',
    'specialistiche': 'speh-chah-LEE-steh-keh',
    'specializzato': 'speh-chah-lee-DZAH-toh',
    'specificata': 'speh-chee-fee-KAH-tah',
    'specifica': 'speh-CHEE-fee-kah',
    'specifiche': 'speh-CHEE-fee-keh',
    'specifici': 'speh-CHEE-fee-chee',
    'specifico': 'speh-CHEE-fee-koh',
    'spediscilo': 'speh-DEE-shee-loh',
    'spenta': 'SPEN-tah',
    'spensierato': 'spen-syeh-RAH-toh',
    'spente': 'SPEN-teh',
    'spento': 'SPEN-toh',
    'sperduto': 'spehr-DOO-toh',
    'sperimentale': 'speh-ree-men-TAH-leh',
    'spessa': 'SPES-sah',
    'spettacolare': 'speht-tah-koh-LAH-reh',
    'spettacolari': 'speht-tah-koh-LAH-ree',
    'spettinato': 'speht-tee-NAH-toh',
    'spezzato': 'speht-TSAH-toh',
    'spiacente': 'spee-ah-CHEN-teh',
    'spiacenti': 'spee-ah-CHEN-tee',
    'spiacevole': 'spee-ah-CHEH-voh-leh',
    'spiccata': 'spee-KAH-tah',
    'spiegazzati': 'spyeh-gah-ZAH-tee',
    'spietata': 'spee-eh-TAH-tah',
    'spietate': 'spee-eh-TAH-teh',
    'spietati': 'spee-eh-TAH-tee',
    'spietato': 'spee-eh-TAH-toh',
    'spinosa': 'spee-NOH-zah',
    'spiritoso': 'spee-ree-TOH-zoh',
    'spirituale': 'spee-ree-too-AH-leh',
    'splendida': 'SPLEN-dee-dah',
    'splendide': 'SPLEN-dee-deh',
    'splendidi': 'SPLEN-dee-dee',
    'splendido': 'SPLEN-dee-doh',
    'spocchiosa': 'spohk-KYOH-zah',
    'spocchiose': 'spohk-KYOH-zeh',
    'spocchiosi': 'spohk-KYOH-zee',
    'spocchioso': 'spohk-KYOH-zoh',
    'spogli': 'SPOH-lyee',
    'spompato': 'spohm-PAH-toh',
    'spontanea': 'spohn-TAH-neh-ah',
    'spontaneo': 'spohn-TAH-neh-oh',
    'sporadici': 'spoh-RAH-dee-chee',
    'sporca': 'SPOR-kah',
    'sporche': 'SPOR-keh',
    'sporchi': 'SPOR-kee',
    'sporco': 'SPOR-koh',
    'sportiva': 'spor-TEE-vah',
    'sportive': 'spor-TEE-veh',
    'sportivi': 'spor-TEE-vee',
    'sportivo': 'spor-TEE-voh',
    'sposati': 'spoh-ZAH-tee',
    'sposata': 'spoh-ZAH-tah',
    'sposate': 'spoh-ZAH-teh',
    'sposato': 'spoh-ZAH-toh',
    'sposini': 'spoh-ZEE-nee',
    'spossante': 'spohs-SAHN-teh',
    'spossato': 'spohs-SAH-toh',
    'sprecato': 'spreh-KAH-toh',
    'spregevole': 'spreh-JEH-voh-leh',
    'spregevoli': 'spreh-JEH-voh-lee',
    'spregiudicato': 'spreh-joo-dee-KAH-toh',
    'sprezzante': 'spret-TSAHN-teh',
    'squallida': 'SKWAHL-lee-dah',
    'squallidi': 'SKWAHL-lee-dee',
    'squilibrati': 'skwee-lee-BRAH-tee',
    'squisita': 'skwee-ZEE-tah',
    'squisito': 'skwee-ZEE-toh',
    'stabile': 'STAH-bee-leh',
    'stabili': 'STAH-bee-lee',
    'stabilita': 'stah-bee-lee-TAH',
    'stagionali': 'stah-joh-NAH-lee',
    'stagnante': 'stahg-NAHN-teh',
    'stampati': 'stahm-PAH-tee',
    'stancante': 'stahn-KAHN-teh',
    'standard': 'STAN-dahrd',
    'stanotte': 'stah-NOHT-teh',
    'stantio': 'stahn-TEE-oh',
    'starnutì': 'stahr-noo-TEE',
    'statale': 'stah-TAH-leh',
    'statistici': 'stah-TEES-tee-chee',
    'statunitense': 'stah-too-nee-TEHN-seh',
    'statunitensi': 'stah-too-nee-TEHN-see',
    'stentato': 'sten-TAH-toh',
    'stereo': 'STEH-ray-oh',
    'sterile': 'STEH-ree-leh',
    'sterili': 'STEH-ree-lee',
    'stimolante': 'stee-moh-LAHN-teh',
    'stomachevole': 'stoh-mah-KEH-voh-leh',
    'stonato': 'stoh-NAH-toh',
    'stordita': 'stor-DEE-tah',
    'stordito': 'stor-DEE-toh',
    'storica': 'STOH-ree-kah',
    'storici': 'STOH-ree-chee',
    'storico': 'STOH-ree-koh',
    'storto': 'STOHR-toh',
    'strabica': 'STRAH-bee-kah',
    'strabico': 'STRAH-bee-koh',
    'stradale': 'strah-DAH-leh',
    'stradali': 'strah-DAH-lee',
    'stragrande': 'strah-GRAHN-deh',
    'strambi': 'STRAM-bee',
    'stramba': 'STRAM-bah',
    'strambo': 'STRAM-boh',
    'strampalata': 'stram-pah-LAH-tah',
    'straordinari': 'strah-or-dee-NAH-ree',
    'straordinaria': 'strah-or-dee-NAH-ryah',
    'straordinarie': 'strah-or-dee-NAH-ryeh',
    'straordinario': 'strah-or-dee-NAH-ryoh',
    'strapazzato': 'strah-paht-TSAH-toh',
    'strappalacrime': 'strah-pah-lah-KREE-meh',
    'stravagante': 'strah-vah-GAHN-teh',
    'straziante': 'strah-TSYAHN-teh',
    'stregata': 'stre-GAH-tah',
    'stremato': 'stre-MAH-toh',
    'strepitoso': 'stre-pee-TOH-zoh',
    'stressante': 'stres-SAHN-teh',
    'stressanti': 'stres-SAHN-tee',
    'stressato': 'stres-SAH-toh',
    'stressati': 'stres-SAH-tee',
    'stressata': 'stres-SAH-tah',
    'stressate': 'stres-SAH-teh',
    'stretta': 'STREHT-tah',
    'strette': 'STREHT-teh',
    'stretti': 'STREHT-tee',
    'stretto': 'STREHT-toh',
    'stridula': 'STREE-doo-lah',
    'strumentale': 'stroo-men-TAH-leh',
    'studentesse': 'stoo-den-TES-seh',
    'studentesca': 'stoo-den-TES-kah',
    'studentesco': 'stoo-den-TES-koh',
    'stufa': 'STOO-fah',
    'stufo': 'STOO-foh',
    'stupefatta': 'stoo-peh-FAHT-tah',
    'stupefatto': 'stoo-peh-FAHT-toh',
    'stupenda': 'stoo-PEHN-dah',
    'stupende': 'stoo-PEHN-deh',
    'stupendi': 'stoo-PEHN-dee',
    'stupendo': 'stoo-PEHN-doh',
    'stupidotto': 'stoo-pee-DOHT-toh',
    'stupito': 'stoo-PEE-toh',
}


def parse_feats(feats):
    data = {}
    if isinstance(feats, str):
        for part in feats.split('|'):
            if '=' in part:
                key, value = part.split('=', 1)
                data[key] = value
    return data


def build_note(feats, gendered):
    gender_note = None
    gender = feats.get('Gender')
    number = feats.get('Number')
    if gendered and gender == 'Masc':
        gender_note = 'masculine'
    elif gendered and gender == 'Fem':
        gender_note = 'feminine'
    if number == 'Plur':
        if gender_note:
            gender_note = f"{gender_note} plural"
        else:
            gender_note = 'plural'
    return gender_note or ''


def main():
    base_path = Path('vocabulary/dataframes/ADJ')

    for lemma, senses in lemma_senses.items():
        path = base_path / f'{lemma}.tsv'
        if not path.exists():
            raise FileNotFoundError(f'Missing TSV for {lemma}: {path}')
        df = pd.read_csv(path, sep='\t')
        genders = set()
        for feats in df['feats']:
            gender = parse_feats(feats).get('Gender')
            if gender in {'Masc', 'Fem'}:
                genders.add(gender)
        gendered = len(genders) > 1

        def translate(row):
            feats = parse_feats(row['feats'])
            note = build_note(feats, gendered)
            if note:
                return f"{senses} ({note})"
            return senses

        def get_pron(text):
            if text not in pronunciations:
                raise ValueError(f'Missing pronunciation for {text}')
            return pronunciations[text]

        df['translation_en'] = df.apply(translate, axis=1)
        df['pronunciation'] = df['text'].map(get_pron)
        df.to_csv(path, sep='\t', index=False)


if __name__ == '__main__':
    main()
